// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  formDataBodySerializer,
  type Options as Options2,
  type TDataShape,
} from "./client";
import { client } from "./client.gen";
import type {
  AddModeratorToStoreData,
  AddModeratorToStoreErrors,
  AddModeratorToStoreResponses,
  CreateStoreCouponData,
  CreateStoreCouponErrors,
  CreateStoreCouponResponses,
  CreateStoreData,
  CreateStoreDiscordEmojisData,
  CreateStoreDiscordEmojisErrors,
  CreateStoreDiscordEmojisResponses,
  CreateStoreDiscordPanelData,
  CreateStoreDiscordPanelErrors,
  CreateStoreDiscordPanelResponses,
  CreateStoreEditOrderData,
  CreateStoreEditOrderErrors,
  CreateStoreEditOrderResponses,
  CreateStoreErrors,
  CreateStoreProductData,
  CreateStoreProductErrors,
  CreateStoreProductResponses,
  CreateStoreRenewOrderData,
  CreateStoreRenewOrderErrors,
  CreateStoreRenewOrderResponses,
  CreateStoreResponses,
  DeleteStoreCouponData,
  DeleteStoreCouponErrors,
  DeleteStoreCouponResponses,
  DeleteStoreDiscordPanelData,
  DeleteStoreDiscordPanelErrors,
  DeleteStoreDiscordPanelResponses,
  DeleteStoreDiscordServerData,
  DeleteStoreDiscordServerErrors,
  DeleteStoreDiscordServerResponses,
  DeleteStoreMediaData,
  DeleteStoreMediaErrors,
  DeleteStoreMediaResponses,
  DeleteStoreProductData,
  DeleteStoreProductErrors,
  DeleteStoreProductResponses,
  EditStoreModeratorData,
  EditStoreModeratorErrors,
  EditStoreModeratorResponses,
  EditUserData,
  EditUserErrors,
  EditUserResponses,
  GetApiReferenceData,
  GetApiReferenceResponses,
  GetServiceApiSchemaData,
  GetServiceApiSchemaResponses,
  GetServiceDataData,
  GetServiceDataResponses,
  GetServiceHealthData,
  GetServiceHealthResponses,
  GetStoreCouponData,
  GetStoreCouponErrors,
  GetStoreCouponResponses,
  GetStoreCouponsData,
  GetStoreCouponsErrors,
  GetStoreCouponsResponses,
  GetStoreData,
  GetStoreDiscordBotData,
  GetStoreDiscordBotErrors,
  GetStoreDiscordBotResponses,
  GetStoreDiscordPanelsData,
  GetStoreDiscordPanelsErrors,
  GetStoreDiscordPanelsResponses,
  GetStoreDiscordServersData,
  GetStoreDiscordServersErrors,
  GetStoreDiscordServersResponses,
  GetStoreErrors,
  GetStoreProductData,
  GetStoreProductErrors,
  GetStoreProductResponses,
  GetStoreProductsData,
  GetStoreProductsErrors,
  GetStoreProductsResponses,
  GetStoreProductStockData,
  GetStoreProductStockErrors,
  GetStoreProductStockResponses,
  GetStoreRankingCustomersData,
  GetStoreRankingCustomersErrors,
  GetStoreRankingCustomersResponses,
  GetStoreResponses,
  GetStoresData,
  GetStoresErrors,
  GetStoresResponses,
  GetStoreStatsProductsData,
  GetStoreStatsProductsErrors,
  GetStoreStatsProductsResponses,
  GetTransactionData,
  GetTransactionErrors,
  GetTransactionResponses,
  GetUserByIdData,
  GetUserByIdErrors,
  GetUserByIdResponses,
  GetUserData,
  GetUserErrors,
  GetUserResponses,
  ListTransactionsData,
  ListTransactionsErrors,
  ListTransactionsResponses,
  PostStoreDiscordPanelMessageData,
  PostStoreDiscordPanelMessageErrors,
  PostStoreDiscordPanelMessageResponses,
  PostStoreProductDiscordMessageData,
  PostStoreProductDiscordMessageErrors,
  PostStoreProductDiscordMessageResponses,
  RemoveStoreModeratorData,
  RemoveStoreModeratorErrors,
  RemoveStoreModeratorResponses,
  SetupEfiData,
  SetupEfiErrors,
  SetupEfiResponses,
  SetupWebhookData,
  SetupWebhookErrors,
  SetupWebhookResponses,
  UpdatePaymentMethodData,
  UpdatePaymentMethodErrors,
  UpdatePaymentMethodResponses,
  UpdatePixKeyData,
  UpdatePixKeyErrors,
  UpdatePixKeyResponses,
  UpdateStoreCouponData,
  UpdateStoreCouponErrors,
  UpdateStoreCouponResponses,
  UpdateStoreData,
  UpdateStoreDiscordBotTokenData,
  UpdateStoreDiscordBotTokenErrors,
  UpdateStoreDiscordBotTokenResponses,
  UpdateStoreDiscordChannelsData,
  UpdateStoreDiscordChannelsErrors,
  UpdateStoreDiscordChannelsResponses,
  UpdateStoreDiscordPanelData,
  UpdateStoreDiscordPanelErrors,
  UpdateStoreDiscordPanelResponses,
  UpdateStoreErrors,
  UpdateStoreProductData,
  UpdateStoreProductErrors,
  UpdateStoreProductResponses,
  UpdateStoreProductStockData,
  UpdateStoreProductStockErrors,
  UpdateStoreProductStockItemData,
  UpdateStoreProductStockItemErrors,
  UpdateStoreProductStockItemResponses,
  UpdateStoreProductStockResponses,
  UpdateStoreResponses,
  UpdateTransactionData,
  UpdateTransactionErrors,
  UpdateTransactionResponses,
  UpdateUserAvatarData,
  UpdateUserAvatarErrors,
  UpdateUserAvatarResponses,
  UploadStoreMediaData,
  UploadStoreMediaErrors,
  UploadStoreMediaResponses,
  WalletBalanceData,
  WalletBalanceErrors,
  WalletBalanceResponses,
  WalletWithdrawData,
  WalletWithdrawErrors,
  WalletWithdrawResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Return service health data, including cache and database status.
 */
export const getServiceHealth = <ThrowOnError extends boolean = false>(
  options?: Options<GetServiceHealthData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetServiceHealthResponses,
    unknown,
    ThrowOnError
  >({ url: "/health", ...options });

/**
 * Return current OpenAPI specification.
 */
export const getServiceApiSchema = <ThrowOnError extends boolean = false>(
  options?: Options<GetServiceApiSchemaData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetServiceApiSchemaResponses,
    unknown,
    ThrowOnError
  >({ url: "/openapi.json", ...options });

/**
 * Delete a store Discord sale panel.
 */
export const deleteStoreDiscordPanel = <ThrowOnError extends boolean = false>(
  options: Options<DeleteStoreDiscordPanelData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteStoreDiscordPanelResponses,
    DeleteStoreDiscordPanelErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/discord_panels/{panelId}",
    ...options,
  });

/**
 * Update a store Discord sale panel.
 */
export const updateStoreDiscordPanel = <ThrowOnError extends boolean = false>(
  options: Options<UpdateStoreDiscordPanelData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    UpdateStoreDiscordPanelResponses,
    UpdateStoreDiscordPanelErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/discord_panels/{panelId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List store Discord sale panels.
 */
export const getStoreDiscordPanels = <ThrowOnError extends boolean = false>(
  options: Options<GetStoreDiscordPanelsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetStoreDiscordPanelsResponses,
    GetStoreDiscordPanelsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/discord_panels",
    ...options,
  });

/**
 * Create a store Discord sale panel.
 */
export const createStoreDiscordPanel = <ThrowOnError extends boolean = false>(
  options: Options<CreateStoreDiscordPanelData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateStoreDiscordPanelResponses,
    CreateStoreDiscordPanelErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/discord_panels",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Ask the store Discord bot to post a panel message in a channel.
 */
export const postStoreDiscordPanelMessage = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PostStoreDiscordPanelMessageData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostStoreDiscordPanelMessageResponses,
    PostStoreDiscordPanelMessageErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/discord_panels/{panelId}/discord_messages",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Ask the store Discord bot to post a product message in a channel.
 */
export const postStoreProductDiscordMessage = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PostStoreProductDiscordMessageData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostStoreProductDiscordMessageResponses,
    PostStoreProductDiscordMessageErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/products/{productId}/discord_messages",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete a store product.
 */
export const deleteStoreProduct = <ThrowOnError extends boolean = false>(
  options: Options<DeleteStoreProductData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteStoreProductResponses,
    DeleteStoreProductErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/products/{productId}",
    ...options,
  });

/**
 * Access a store product.
 */
export const getStoreProduct = <ThrowOnError extends boolean = false>(
  options: Options<GetStoreProductData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetStoreProductResponses,
    GetStoreProductErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/products/{productId}",
    ...options,
  });

/**
 * Update a store product.
 */
export const updateStoreProduct = <ThrowOnError extends boolean = false>(
  options: Options<UpdateStoreProductData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    UpdateStoreProductResponses,
    UpdateStoreProductErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/products/{productId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List products from a store.
 */
export const getStoreProducts = <ThrowOnError extends boolean = false>(
  options: Options<GetStoreProductsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetStoreProductsResponses,
    GetStoreProductsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/products",
    ...options,
  });

/**
 * Create a store product.
 */
export const createStoreProduct = <ThrowOnError extends boolean = false>(
  options: Options<CreateStoreProductData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateStoreProductResponses,
    CreateStoreProductErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/products",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Update a product stock item.
 */
export const updateStoreProductStockItem = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateStoreProductStockItemData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    UpdateStoreProductStockItemResponses,
    UpdateStoreProductStockItemErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/products/{productId}/stock/{stockId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List available stock items for a product.
 */
export const getStoreProductStock = <ThrowOnError extends boolean = false>(
  options: Options<GetStoreProductStockData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetStoreProductStockResponses,
    GetStoreProductStockErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/products/{productId}/stock",
    ...options,
  });

/**
 * Add or remove product stock items and update stock lock settings.
 */
export const updateStoreProductStock = <ThrowOnError extends boolean = false>(
  options: Options<UpdateStoreProductStockData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    UpdateStoreProductStockResponses,
    UpdateStoreProductStockErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/products/{productId}/stock",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Return current OpenAPI specification.
 */
export const getApiReference = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiReferenceData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetApiReferenceResponses,
    unknown,
    ThrowOnError
  >({ url: "/reference", ...options });

/**
 * Returns basic service data, focused on website functionality (such as home statistics), but is a public route.
 */
export const getServiceData = <ThrowOnError extends boolean = false>(
  options?: Options<GetServiceDataData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetServiceDataResponses,
    unknown,
    ThrowOnError
  >({ url: "/service", ...options });

/**
 * Update store Discord channel bindings.
 */
export const updateStoreDiscordChannels = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateStoreDiscordChannelsData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    UpdateStoreDiscordChannelsResponses,
    UpdateStoreDiscordChannelsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/app/discord/channels",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Create Discord emojis in a store bot guild.
 */
export const createStoreDiscordEmojis = <ThrowOnError extends boolean = false>(
  options: Options<CreateStoreDiscordEmojisData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateStoreDiscordEmojisResponses,
    CreateStoreDiscordEmojisErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/app/discord/{serverId}/emojis",
    ...options,
    headers: {
      "Content-Type": null,
      ...options.headers,
    },
  });

/**
 * Get the configured Discord bot status for a store.
 */
export const getStoreDiscordBot = <ThrowOnError extends boolean = false>(
  options: Options<GetStoreDiscordBotData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetStoreDiscordBotResponses,
    GetStoreDiscordBotErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/app/discord",
    ...options,
  });

/**
 * Remove a store Discord bot from a guild.
 */
export const deleteStoreDiscordServer = <ThrowOnError extends boolean = false>(
  options: Options<DeleteStoreDiscordServerData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteStoreDiscordServerResponses,
    DeleteStoreDiscordServerErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/app/discord/servers",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Discord guilds cached for a store bot.
 */
export const getStoreDiscordServers = <ThrowOnError extends boolean = false>(
  options: Options<GetStoreDiscordServersData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetStoreDiscordServersResponses,
    GetStoreDiscordServersErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/app/discord/servers",
    ...options,
  });

/**
 * Update a store Discord bot token.
 */
export const updateStoreDiscordBotToken = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateStoreDiscordBotTokenData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    UpdateStoreDiscordBotTokenResponses,
    UpdateStoreDiscordBotTokenErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/app/discord/token",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete a store coupon.
 */
export const deleteStoreCoupon = <ThrowOnError extends boolean = false>(
  options: Options<DeleteStoreCouponData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteStoreCouponResponses,
    DeleteStoreCouponErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/coupons/{couponId}",
    ...options,
  });

/**
 * Access a store coupon.
 */
export const getStoreCoupon = <ThrowOnError extends boolean = false>(
  options: Options<GetStoreCouponData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetStoreCouponResponses,
    GetStoreCouponErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/coupons/{couponId}",
    ...options,
  });

/**
 * Update a store coupon.
 */
export const updateStoreCoupon = <ThrowOnError extends boolean = false>(
  options: Options<UpdateStoreCouponData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    UpdateStoreCouponResponses,
    UpdateStoreCouponErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/coupons/{couponId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List store coupons.
 */
export const getStoreCoupons = <ThrowOnError extends boolean = false>(
  options: Options<GetStoreCouponsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetStoreCouponsResponses,
    GetStoreCouponsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/coupons",
    ...options,
  });

/**
 * Create a store coupon.
 */
export const createStoreCoupon = <ThrowOnError extends boolean = false>(
  options: Options<CreateStoreCouponData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateStoreCouponResponses,
    CreateStoreCouponErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/coupons",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Create an order to edit store addons or limits.
 */
export const createStoreEditOrder = <ThrowOnError extends boolean = false>(
  options: Options<CreateStoreEditOrderData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateStoreEditOrderResponses,
    CreateStoreEditOrderErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/financial/edit",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Create an order to renew a store.
 */
export const createStoreRenewOrder = <ThrowOnError extends boolean = false>(
  options: Options<CreateStoreRenewOrderData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateStoreRenewOrderResponses,
    CreateStoreRenewOrderErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/financial/renew",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Detach media from store entities.
 */
export const deleteStoreMedia = <ThrowOnError extends boolean = false>(
  options: Options<DeleteStoreMediaData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteStoreMediaResponses,
    DeleteStoreMediaErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/media",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Upload a media file and attach it to store entities.
 */
export const uploadStoreMedia = <ThrowOnError extends boolean = false>(
  options: Options<UploadStoreMediaData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    UploadStoreMediaResponses,
    UploadStoreMediaErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/media",
    ...options,
    headers: {
      "Content-Type": null,
      ...options.headers,
    },
  });

/**
 * Delete a store moderator.
 */
export const removeStoreModerator = <ThrowOnError extends boolean = false>(
  options: Options<RemoveStoreModeratorData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    RemoveStoreModeratorResponses,
    RemoveStoreModeratorErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/moderators/{modId}",
    ...options,
  });

/**
 * Update a store moderator.
 */
export const editStoreModerator = <ThrowOnError extends boolean = false>(
  options: Options<EditStoreModeratorData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    EditStoreModeratorResponses,
    EditStoreModeratorErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/moderators/{modId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Create a store moderator invite.
 */
export const addModeratorToStore = <ThrowOnError extends boolean = false>(
  options: Options<AddModeratorToStoreData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    AddModeratorToStoreResponses,
    AddModeratorToStoreErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/moderators",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Access store customers ranking, updated in real time.
 */
export const getStoreRankingCustomers = <ThrowOnError extends boolean = false>(
  options: Options<GetStoreRankingCustomersData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetStoreRankingCustomersResponses,
    GetStoreRankingCustomersErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/ranking/customers",
    ...options,
  });

/**
 * Access store product statistics, real-time updated.
 */
export const getStoreStatsProducts = <ThrowOnError extends boolean = false>(
  options: Options<GetStoreStatsProductsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetStoreStatsProductsResponses,
    GetStoreStatsProductsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/stats/products",
    ...options,
  });

/**
 * Access store data.
 */
export const getStore = <ThrowOnError extends boolean = false>(
  options: Options<GetStoreData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetStoreResponses,
    GetStoreErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}",
    ...options,
  });

/**
 * Update store settings.
 */
export const updateStore = <ThrowOnError extends boolean = false>(
  options: Options<UpdateStoreData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    UpdateStoreResponses,
    UpdateStoreErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List stores owned or moderated by the current user.
 */
export const getStores = <ThrowOnError extends boolean = false>(
  options?: Options<GetStoresData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetStoresResponses,
    GetStoresErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores",
    ...options,
  });

/**
 * Create a checkout order for a new store.
 */
export const createStore = <ThrowOnError extends boolean = false>(
  options?: Options<CreateStoreData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    CreateStoreResponses,
    CreateStoreErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });

/**
 * List transactions for the authenticated user.
 */
export const listTransactions = <ThrowOnError extends boolean = false>(
  options?: Options<ListTransactionsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListTransactionsResponses,
    ListTransactionsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/transactions",
    ...options,
  });

/**
 * Access a transaction by id or Pix E2E id.
 */
export const getTransaction = <ThrowOnError extends boolean = false>(
  options: Options<GetTransactionData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetTransactionResponses,
    GetTransactionErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/transactions/{transactionId}",
    ...options,
  });

/**
 * Update transaction status or metadata.
 */
export const updateTransaction = <ThrowOnError extends boolean = false>(
  options: Options<UpdateTransactionData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    UpdateTransactionResponses,
    UpdateTransactionErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/transactions/{transactionId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Access current user data
 */
export const getUserById = <ThrowOnError extends boolean = false>(
  options: Options<GetUserByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetUserByIdResponses,
    GetUserByIdErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/{userId}",
    ...options,
  });

/**
 * Update users's avatar
 */
export const updateUserAvatar = <ThrowOnError extends boolean = false>(
  options?: Options<UpdateUserAvatarData, ThrowOnError>,
) =>
  (options?.client ?? client).patch<
    UpdateUserAvatarResponses,
    UpdateUserAvatarErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/me/avatar",
    ...options,
    headers: {
      "Content-Type": null,
      ...options?.headers,
    },
  });

/**
 * Access current user data
 */
export const getUser = <ThrowOnError extends boolean = false>(
  options?: Options<GetUserData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetUserResponses,
    GetUserErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/me",
    ...options,
  });

/**
 * Edit current user data
 */
export const editUser = <ThrowOnError extends boolean = false>(
  options?: Options<EditUserData, ThrowOnError>,
) =>
  (options?.client ?? client).patch<
    EditUserResponses,
    EditUserErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/me",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });

/**
 * Update the user's preferred payment method.
 */
export const updatePaymentMethod = <ThrowOnError extends boolean = false>(
  options?: Options<UpdatePaymentMethodData, ThrowOnError>,
) =>
  (options?.client ?? client).patch<
    UpdatePaymentMethodResponses,
    UpdatePaymentMethodErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/me/payment-method",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });

/**
 * Configures the user's Efí account with certificate, Pix key, and OAuth credentials.
 */
export const setupEfi = <ThrowOnError extends boolean = false>(
  options?: Options<SetupEfiData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    SetupEfiResponses,
    SetupEfiErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/me/payments/efi/setup",
    ...options,
    headers: {
      "Content-Type": null,
      ...options?.headers,
    },
  });

/**
 * Update the user's semiauto Pix key.
 */
export const updatePixKey = <ThrowOnError extends boolean = false>(
  options?: Options<UpdatePixKeyData, ThrowOnError>,
) =>
  (options?.client ?? client).patch<
    UpdatePixKeyResponses,
    UpdatePixKeyErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/me/pix_key",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });

/**
 * Returns the user's Zennify Wallet balance.
 */
export const walletBalance = <ThrowOnError extends boolean = false>(
  options?: Options<WalletBalanceData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    WalletBalanceResponses,
    WalletBalanceErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/me/wallet/balance",
    ...options,
  });

/**
 * Requests a withdrawal from the user's Zennify Wallet.
 */
export const walletWithdraw = <ThrowOnError extends boolean = false>(
  options?: Options<WalletWithdrawData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    WalletWithdrawResponses,
    WalletWithdrawErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/me/wallet/withdraw",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });

/**
 * Setup an HTTP webhook for the user.
 */
export const setupWebhook = <ThrowOnError extends boolean = false>(
  options?: Options<SetupWebhookData, ThrowOnError>,
) =>
  (options?.client ?? client).patch<
    SetupWebhookResponses,
    SetupWebhookErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/me/webhook",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
