// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  formDataBodySerializer,
  type Options as Options2,
  type TDataShape,
} from "./client";
import { client } from "./client.gen";
import type {
  CreateCouponData,
  CreateCouponErrors,
  CreateCouponResponses,
  CreateDiscordAppAutoReactData,
  CreateDiscordAppAutoReactErrors,
  CreateDiscordAppAutoReactResponses,
  CreateDiscordAppAutoRoleData,
  CreateDiscordAppAutoRoleErrors,
  CreateDiscordAppAutoRoleResponses,
  CreateProductCatalogData,
  CreateProductCatalogErrors,
  CreateProductCatalogResponses,
  CreateProductData,
  CreateProductErrors,
  CreateProductResponses,
  DeleteCouponData,
  DeleteCouponErrors,
  DeleteCouponResponses,
  DeleteDiscordAppAutoReactData,
  DeleteDiscordAppAutoReactErrors,
  DeleteDiscordAppAutoReactResponses,
  DeleteDiscordAppAutoRoleData,
  DeleteDiscordAppAutoRoleErrors,
  DeleteDiscordAppAutoRoleResponses,
  DeleteMediaData,
  DeleteMediaErrors,
  DeleteMediaResponses,
  DeleteProductCatalogData,
  DeleteProductCatalogErrors,
  DeleteProductCatalogResponses,
  DeleteProductData,
  DeleteProductErrors,
  DeleteProductResponses,
  EditCouponData,
  EditCouponErrors,
  EditCouponResponses,
  EditDiscordAppAutoCrosspostData,
  EditDiscordAppAutoCrosspostErrors,
  EditDiscordAppAutoCrosspostResponses,
  EditDiscordAppAutoReactData,
  EditDiscordAppAutoReactErrors,
  EditDiscordAppAutoReactResponses,
  EditDiscordAppAutoRoleData,
  EditDiscordAppAutoRoleErrors,
  EditDiscordAppAutoRoleResponses,
  EditDiscordAppChannelsData,
  EditDiscordAppChannelsErrors,
  EditDiscordAppChannelsResponses,
  EditDiscordAppTokenData,
  EditDiscordAppTokenErrors,
  EditDiscordAppTokenResponses,
  EditProductCatalogData,
  EditProductCatalogErrors,
  EditProductCatalogResponses,
  EditProductData,
  EditProductErrors,
  EditProductResponses,
  EditProductStockData,
  EditProductStockErrors,
  EditProductStockItemData,
  EditProductStockItemErrors,
  EditProductStockItemResponses,
  EditProductStockResponses,
  EditStoreData,
  EditStoreErrors,
  EditStoreResponses,
  EditTransactionData,
  EditTransactionErrors,
  EditTransactionResponses,
  EditUserAvatarData,
  EditUserAvatarErrors,
  EditUserAvatarResponses,
  EditUserData,
  EditUserErrors,
  EditUserPaymentMethodData,
  EditUserPaymentMethodErrors,
  EditUserPaymentMethodResponses,
  EditUserResponses,
  GetCouponData,
  GetCouponErrors,
  GetCouponHistoryData,
  GetCouponHistoryErrors,
  GetCouponHistoryResponses,
  GetCouponResponses,
  GetDiscordAppEmojisData,
  GetDiscordAppEmojisErrors,
  GetDiscordAppEmojisResponses,
  GetDiscordAppInfoData,
  GetDiscordAppInfoErrors,
  GetDiscordAppInfoResponses,
  GetDiscordAppRolesData,
  GetDiscordAppRolesErrors,
  GetDiscordAppRolesResponses,
  GetDiscordAppServersData,
  GetDiscordAppServersErrors,
  GetDiscordAppServersResponses,
  GetProductData,
  GetProductErrors,
  GetProductHistoryData,
  GetProductHistoryErrors,
  GetProductHistoryResponses,
  GetProductResponses,
  GetProductStockData,
  GetProductStockErrors,
  GetProductStockResponses,
  GetServiceApiSchemaData,
  GetServiceApiSchemaResponses,
  GetServiceDataData,
  GetServiceDataResponses,
  GetServiceHealthData,
  GetServiceHealthResponses,
  GetStoreData,
  GetStoreErrors,
  GetStoreRankingCustomersData,
  GetStoreRankingCustomersErrors,
  GetStoreRankingCustomersResponses,
  GetStoreResponses,
  GetStoreStatsCouponsData,
  GetStoreStatsCouponsErrors,
  GetStoreStatsCouponsResponses,
  GetStoreStatsProductsData,
  GetStoreStatsProductsErrors,
  GetStoreStatsProductsResponses,
  GetStoreStatsSalesData,
  GetStoreStatsSalesErrors,
  GetStoreStatsSalesResponses,
  GetTransactionData,
  GetTransactionErrors,
  GetTransactionResponses,
  GetUserByIdData,
  GetUserByIdErrors,
  GetUserByIdResponses,
  GetUserData,
  GetUserErrors,
  GetUserResponses,
  ListCouponsData,
  ListCouponsErrors,
  ListCouponsResponses,
  ListProductCatalogsData,
  ListProductCatalogsErrors,
  ListProductCatalogsResponses,
  ListProductsData,
  ListProductsErrors,
  ListProductsResponses,
  ListStoresData,
  ListStoresErrors,
  ListStoresResponses,
  ListTransactionsData,
  ListTransactionsErrors,
  ListTransactionsResponses,
  RateTransactionData,
  RateTransactionErrors,
  RateTransactionResponses,
  RefundTransactionData,
  RefundTransactionErrors,
  RefundTransactionResponses,
  SendProductCatalogMessageData,
  SendProductCatalogMessageErrors,
  SendProductCatalogMessageResponses,
  SendProductDiscordMessageData,
  SendProductDiscordMessageErrors,
  SendProductDiscordMessageResponses,
  SetupEfiData,
  SetupEfiErrors,
  SetupEfiResponses,
  SetupSemiautoData,
  SetupSemiautoErrors,
  SetupSemiautoResponses,
  UploadStoreMediaData,
  UploadStoreMediaErrors,
  UploadStoreMediaResponses,
  WalletBalanceData,
  WalletBalanceErrors,
  WalletBalanceResponses,
  WalletWithdrawData,
  WalletWithdrawErrors,
  WalletWithdrawResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Return service health data, including cache and database status.
 */
export const getServiceHealth = <ThrowOnError extends boolean = false>(
  options?: Options<GetServiceHealthData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetServiceHealthResponses,
    unknown,
    ThrowOnError
  >({ url: "/health", ...options });

/**
 * Return current OpenAPI specification.
 */
export const getServiceApiSchema = <ThrowOnError extends boolean = false>(
  options?: Options<GetServiceApiSchemaData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetServiceApiSchemaResponses,
    unknown,
    ThrowOnError
  >({ url: "/openapi.json", ...options });

/**
 * Returns basic service data, focused on website functionality (such as home statistics), but is a public route.
 */
export const getServiceData = <ThrowOnError extends boolean = false>(
  options?: Options<GetServiceDataData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetServiceDataResponses,
    unknown,
    ThrowOnError
  >({ url: "/service", ...options });

/**
 * Access public data of a user by id.
 */
export const getUserById = <ThrowOnError extends boolean = false>(
  options: Options<GetUserByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetUserByIdResponses,
    GetUserByIdErrors,
    ThrowOnError
  >({ url: "/users/{userId}", ...options });

/**
 * List product delivery history (sales + manual deliveries) for auditing.
 */
export const getProductHistory = <ThrowOnError extends boolean = false>(
  options: Options<GetProductHistoryData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetProductHistoryResponses,
    GetProductHistoryErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/products/{productId}/history",
    ...options,
  });

/**
 * Ask the store Discord bot to post a product message in a channel.
 */
export const sendProductDiscordMessage = <ThrowOnError extends boolean = false>(
  options: Options<SendProductDiscordMessageData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    SendProductDiscordMessageResponses,
    SendProductDiscordMessageErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/products/{productId}/discord_messages",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete a store product.
 */
export const deleteProduct = <ThrowOnError extends boolean = false>(
  options: Options<DeleteProductData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteProductResponses,
    DeleteProductErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/products/{productId}",
    ...options,
  });

/**
 * Access a store product.
 */
export const getProduct = <ThrowOnError extends boolean = false>(
  options: Options<GetProductData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetProductResponses,
    GetProductErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/products/{productId}",
    ...options,
  });

/**
 * Update a store product.
 */
export const editProduct = <ThrowOnError extends boolean = false>(
  options: Options<EditProductData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    EditProductResponses,
    EditProductErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/products/{productId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List products from a store.
 */
export const listProducts = <ThrowOnError extends boolean = false>(
  options: Options<ListProductsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    ListProductsResponses,
    ListProductsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/products",
    ...options,
  });

/**
 * Create a store product.
 */
export const createProduct = <ThrowOnError extends boolean = false>(
  options: Options<CreateProductData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateProductResponses,
    CreateProductErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/products",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Update a product stock item.
 */
export const editProductStockItem = <ThrowOnError extends boolean = false>(
  options: Options<EditProductStockItemData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    EditProductStockItemResponses,
    EditProductStockItemErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/products/{productId}/stock/{stockId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List available stock items for a product.
 */
export const getProductStock = <ThrowOnError extends boolean = false>(
  options: Options<GetProductStockData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetProductStockResponses,
    GetProductStockErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/products/{productId}/stock",
    ...options,
  });

/**
 * Add or remove product stock items and update stock lock/delivery settings.
 */
export const editProductStock = <ThrowOnError extends boolean = false>(
  options: Options<EditProductStockData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    EditProductStockResponses,
    EditProductStockErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/products/{productId}/stock",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Update a store auto crosspost configuration.
 */
export const editDiscordAppAutoCrosspost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<EditDiscordAppAutoCrosspostData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    EditDiscordAppAutoCrosspostResponses,
    EditDiscordAppAutoCrosspostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/app/discord/auto/crosspost",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete a store channel auto react configuration.
 */
export const deleteDiscordAppAutoReact = <ThrowOnError extends boolean = false>(
  options: Options<DeleteDiscordAppAutoReactData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteDiscordAppAutoReactResponses,
    DeleteDiscordAppAutoReactErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/app/discord/auto/react",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Update an existing store channel auto react configuration.
 */
export const editDiscordAppAutoReact = <ThrowOnError extends boolean = false>(
  options: Options<EditDiscordAppAutoReactData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    EditDiscordAppAutoReactResponses,
    EditDiscordAppAutoReactErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/app/discord/auto/react",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Create a store channel auto react configuration.
 */
export const createDiscordAppAutoReact = <ThrowOnError extends boolean = false>(
  options: Options<CreateDiscordAppAutoReactData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateDiscordAppAutoReactResponses,
    CreateDiscordAppAutoReactErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/app/discord/auto/react",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Create a store auto role rule.
 */
export const createDiscordAppAutoRole = <ThrowOnError extends boolean = false>(
  options: Options<CreateDiscordAppAutoRoleData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateDiscordAppAutoRoleResponses,
    CreateDiscordAppAutoRoleErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/app/discord/auto/roles",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete (soft) a store auto role rule.
 */
export const deleteDiscordAppAutoRole = <ThrowOnError extends boolean = false>(
  options: Options<DeleteDiscordAppAutoRoleData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteDiscordAppAutoRoleResponses,
    DeleteDiscordAppAutoRoleErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/app/discord/auto/roles/{ruleId}",
    ...options,
  });

/**
 * Update a store auto role rule.
 */
export const editDiscordAppAutoRole = <ThrowOnError extends boolean = false>(
  options: Options<EditDiscordAppAutoRoleData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    EditDiscordAppAutoRoleResponses,
    EditDiscordAppAutoRoleErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/app/discord/auto/roles/{ruleId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Update store Discord channel bindings.
 */
export const editDiscordAppChannels = <ThrowOnError extends boolean = false>(
  options: Options<EditDiscordAppChannelsData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    EditDiscordAppChannelsResponses,
    EditDiscordAppChannelsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/app/discord/channels",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get all cached store emojis
 */
export const getDiscordAppEmojis = <ThrowOnError extends boolean = false>(
  options: Options<GetDiscordAppEmojisData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetDiscordAppEmojisResponses,
    GetDiscordAppEmojisErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/app/discord/emojis",
    ...options,
  });

/**
 * Get the configured Discord app info & status for a store.
 */
export const getDiscordAppInfo = <ThrowOnError extends boolean = false>(
  options: Options<GetDiscordAppInfoData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetDiscordAppInfoResponses,
    GetDiscordAppInfoErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/app/discord",
    ...options,
  });

/**
 * Get Discord App roles, by guilds.
 */
export const getDiscordAppRoles = <ThrowOnError extends boolean = false>(
  options: Options<GetDiscordAppRolesData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetDiscordAppRolesResponses,
    GetDiscordAppRolesErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/app/discord/roles",
    ...options,
  });

/**
 * List Discord guilds cached for a store app.
 */
export const getDiscordAppServers = <ThrowOnError extends boolean = false>(
  options: Options<GetDiscordAppServersData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetDiscordAppServersResponses,
    GetDiscordAppServersErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/app/discord/servers",
    ...options,
  });

/**
 * Update a store Discord bot token.
 */
export const editDiscordAppToken = <ThrowOnError extends boolean = false>(
  options: Options<EditDiscordAppTokenData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    EditDiscordAppTokenResponses,
    EditDiscordAppTokenErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/app/discord/token",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete a store product catalog.
 */
export const deleteProductCatalog = <ThrowOnError extends boolean = false>(
  options: Options<DeleteProductCatalogData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteProductCatalogResponses,
    DeleteProductCatalogErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/catalogs/{catalogId}",
    ...options,
  });

/**
 * Update a store product catalog.
 */
export const editProductCatalog = <ThrowOnError extends boolean = false>(
  options: Options<EditProductCatalogData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    EditProductCatalogResponses,
    EditProductCatalogErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/catalogs/{catalogId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List store product catalogs.
 */
export const listProductCatalogs = <ThrowOnError extends boolean = false>(
  options: Options<ListProductCatalogsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    ListProductCatalogsResponses,
    ListProductCatalogsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/catalogs",
    ...options,
  });

/**
 * Create a store product catalog.
 */
export const createProductCatalog = <ThrowOnError extends boolean = false>(
  options: Options<CreateProductCatalogData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateProductCatalogResponses,
    CreateProductCatalogErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/catalogs",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Ask the store Discord bot to post a catalog message in a channel.
 */
export const sendProductCatalogMessage = <ThrowOnError extends boolean = false>(
  options: Options<SendProductCatalogMessageData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    SendProductCatalogMessageResponses,
    SendProductCatalogMessageErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/catalogs/{catalogId}/discord_messages",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete a store coupon.
 */
export const deleteCoupon = <ThrowOnError extends boolean = false>(
  options: Options<DeleteCouponData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteCouponResponses,
    DeleteCouponErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/coupons/{couponId}",
    ...options,
  });

/**
 * Access a store coupon.
 */
export const getCoupon = <ThrowOnError extends boolean = false>(
  options: Options<GetCouponData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetCouponResponses,
    GetCouponErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/coupons/{couponId}",
    ...options,
  });

/**
 * Update a store coupon.
 */
export const editCoupon = <ThrowOnError extends boolean = false>(
  options: Options<EditCouponData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    EditCouponResponses,
    EditCouponErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/coupons/{couponId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List store coupons.
 */
export const listCoupons = <ThrowOnError extends boolean = false>(
  options: Options<ListCouponsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    ListCouponsResponses,
    ListCouponsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/coupons",
    ...options,
  });

/**
 * Create a store coupon.
 */
export const createCoupon = <ThrowOnError extends boolean = false>(
  options: Options<CreateCouponData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateCouponResponses,
    CreateCouponErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/coupons",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List transactions where this coupon was applied, for auditing.
 */
export const getCouponHistory = <ThrowOnError extends boolean = false>(
  options: Options<GetCouponHistoryData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetCouponHistoryResponses,
    GetCouponHistoryErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/coupons/{couponId}/history",
    ...options,
  });

/**
 * Detach media from store entities.
 */
export const deleteMedia = <ThrowOnError extends boolean = false>(
  options: Options<DeleteMediaData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteMediaResponses,
    DeleteMediaErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/media",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Upload a media file and attach it to store entities.
 */
export const uploadStoreMedia = <ThrowOnError extends boolean = false>(
  options: Options<UploadStoreMediaData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    UploadStoreMediaResponses,
    UploadStoreMediaErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/media",
    ...options,
    headers: {
      "Content-Type": null,
      ...options.headers,
    },
  });

/**
 * Access store customers ranking, updated in real time.
 */
export const getStoreRankingCustomers = <ThrowOnError extends boolean = false>(
  options: Options<GetStoreRankingCustomersData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetStoreRankingCustomersResponses,
    GetStoreRankingCustomersErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/ranking/customers",
    ...options,
  });

/**
 * Access store coupon statistics (per-coupon totals + daily history), real-time updated.
 */
export const getStoreStatsCoupons = <ThrowOnError extends boolean = false>(
  options: Options<GetStoreStatsCouponsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetStoreStatsCouponsResponses,
    GetStoreStatsCouponsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/stats/coupons",
    ...options,
  });

/**
 * Access store product statistics, real-time updated.
 */
export const getStoreStatsProducts = <ThrowOnError extends boolean = false>(
  options: Options<GetStoreStatsProductsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetStoreStatsProductsResponses,
    GetStoreStatsProductsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/stats/products",
    ...options,
  });

/**
 * Access store sales statistics grouped by day, real-time updated.
 */
export const getStoreStatsSales = <ThrowOnError extends boolean = false>(
  options: Options<GetStoreStatsSalesData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetStoreStatsSalesResponses,
    GetStoreStatsSalesErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}/stats/sales",
    ...options,
  });

/**
 * Access store data.
 */
export const getStore = <ThrowOnError extends boolean = false>(
  options: Options<GetStoreData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetStoreResponses,
    GetStoreErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}",
    ...options,
  });

/**
 * Update store settings.
 */
export const editStore = <ThrowOnError extends boolean = false>(
  options: Options<EditStoreData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    EditStoreResponses,
    EditStoreErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores/{storeId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List stores owned or moderated by the current user.
 */
export const listStores = <ThrowOnError extends boolean = false>(
  options?: Options<ListStoresData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListStoresResponses,
    ListStoresErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/stores",
    ...options,
  });

/**
 * Rate a sale transaction as its payer. Allowed until 90 days after purchase; a 5-star rating locks further edits.
 */
export const rateTransaction = <ThrowOnError extends boolean = false>(
  options: Options<RateTransactionData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    RateTransactionResponses,
    RateTransactionErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/transactions/{transactionId}/rating",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Refund a sale transaction, fully or partially.
 */
export const refundTransaction = <ThrowOnError extends boolean = false>(
  options: Options<RefundTransactionData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    RefundTransactionResponses,
    RefundTransactionErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/transactions/{transactionId}/refund",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Access a transaction by id or Pix E2E id.
 */
export const getTransaction = <ThrowOnError extends boolean = false>(
  options: Options<GetTransactionData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetTransactionResponses,
    GetTransactionErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/transactions/{transactionId}",
    ...options,
  });

/**
 * Update transaction status or metadata.
 */
export const editTransaction = <ThrowOnError extends boolean = false>(
  options: Options<EditTransactionData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    EditTransactionResponses,
    EditTransactionErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/transactions/{transactionId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List transactions for the authenticated user.
 */
export const listTransactions = <ThrowOnError extends boolean = false>(
  options?: Options<ListTransactionsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListTransactionsResponses,
    ListTransactionsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/transactions",
    ...options,
  });

/**
 * Update users's avatar
 */
export const editUserAvatar = <ThrowOnError extends boolean = false>(
  options?: Options<EditUserAvatarData, ThrowOnError>,
) =>
  (options?.client ?? client).patch<
    EditUserAvatarResponses,
    EditUserAvatarErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/me/avatar",
    ...options,
    headers: {
      "Content-Type": null,
      ...options?.headers,
    },
  });

/**
 * Access current user data
 */
export const getUser = <ThrowOnError extends boolean = false>(
  options?: Options<GetUserData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetUserResponses,
    GetUserErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/me",
    ...options,
  });

/**
 * Edit current user data
 */
export const editUser = <ThrowOnError extends boolean = false>(
  options?: Options<EditUserData, ThrowOnError>,
) =>
  (options?.client ?? client).patch<
    EditUserResponses,
    EditUserErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/me",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });

/**
 * Update the user's preferred payment method.
 */
export const editUserPaymentMethod = <ThrowOnError extends boolean = false>(
  options?: Options<EditUserPaymentMethodData, ThrowOnError>,
) =>
  (options?.client ?? client).patch<
    EditUserPaymentMethodResponses,
    EditUserPaymentMethodErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/me/payment-method",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });

/**
 * Configures the user's Efí account with certificate, Pix key, and OAuth credentials.
 */
export const setupEfi = <ThrowOnError extends boolean = false>(
  options?: Options<SetupEfiData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    SetupEfiResponses,
    SetupEfiErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/me/payments/efi/setup",
    ...options,
    headers: {
      "Content-Type": null,
      ...options?.headers,
    },
  });

/**
 * Create semiauto integration for user.
 */
export const setupSemiauto = <ThrowOnError extends boolean = false>(
  options?: Options<SetupSemiautoData, ThrowOnError>,
) =>
  (options?.client ?? client).patch<
    SetupSemiautoResponses,
    SetupSemiautoErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/me/payments/semiauto",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });

/**
 * Returns the user's Zennify Wallet balance.
 */
export const walletBalance = <ThrowOnError extends boolean = false>(
  options?: Options<WalletBalanceData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    WalletBalanceResponses,
    WalletBalanceErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/me/wallet/balance",
    ...options,
  });

/**
 * Requests a withdrawal from the user's Zennify Wallet.
 */
export const walletWithdraw = <ThrowOnError extends boolean = false>(
  options?: Options<WalletWithdrawData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    WalletWithdrawResponses,
    WalletWithdrawErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/me/wallet/withdraw",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
