// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "https://api.zennify.app" | (string & {});
};

export type DefaultError = {
  code: string;
  title: string;
  message: string;
};

export type GetServiceHealthData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/health";
};

export type GetServiceHealthResponses = {
  /**
   * All running fine :)
   */
  200: {
    fine: boolean;
    cache: boolean;
    database: boolean;
  };
};

export type GetServiceHealthResponse =
  GetServiceHealthResponses[keyof GetServiceHealthResponses];

export type GetServiceApiSchemaData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/openapi.json";
};

export type GetServiceApiSchemaResponses = {
  /**
   * Success, good work with our API :)
   */
  200: unknown;
};

export type GetServiceDataData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/service";
};

export type GetServiceDataResponses = {
  /**
   * Success - Get service data
   */
  200: {
    servers: {
      top: Array<{
        /**
         * Discord server id.
         */
        id: string;
        /**
         * Discord server name.
         */
        name: string;
        /**
         * Discord server member count.
         */
        members: number;
        icon_url: null | string;
      }>;
      random: Array<{
        /**
         * Discord server id.
         */
        id: string;
        /**
         * Discord server name.
         */
        name: string;
        /**
         * Discord server member count.
         */
        members: number;
        icon_url: null | string;
      }>;
    };
    pricing: {
      /**
       * Store plan price.
       */
      store: number;
      /**
       * Store renewal price.
       */
      renew: number;
      limits: {
        /**
         * Discord server limit price.
         */
        discord_server: number;
        /**
         * Product limit price.
         */
        product: number;
      };
    };
    statistics: {
      /**
       * Service revenue.
       */
      revenue: number;
      /**
       * Store count.
       */
      stores: number;
      /**
       * Sales count.
       */
      sales: number;
      /**
       * User count.
       */
      users: number;
    };
  };
};

export type GetServiceDataResponse =
  GetServiceDataResponses[keyof GetServiceDataResponses];

export type GetUserByIdData = {
  body?: never;
  path: {
    userId: string;
  };
  query?: never;
  url: "/users/{userId}";
};

export type GetUserByIdErrors = {
  /**
   * User not found.
   */
  404: DefaultError;
  /**
   * Too many requests.
   */
  429: DefaultError;
};

export type GetUserByIdError = GetUserByIdErrors[keyof GetUserByIdErrors];

export type GetUserByIdResponses = {
  /**
   * User returned successfully.
   */
  200: {
    /**
     * User id.
     */
    id: number;
    /**
     * Public user name.
     */
    name: string;
    avatar: null | string;
    connections: {
      discord: null | string;
    };
    /**
     * User join timestamp.
     */
    joined_at: number;
    verified: boolean;
    is_admin: boolean;
    stores: Array<{
      /**
       * Store id.
       */
      id: number;
      /**
       * Store name.
       */
      name: string;
      icon_id: null | string;
      banner_id: null | string;
      /**
       * Store creation timestamp.
       */
      created_at: number;
      rating: null | number;
    }>;
  };
};

export type GetUserByIdResponse =
  GetUserByIdResponses[keyof GetUserByIdResponses];

export type EditUserAvatarData = {
  body?: {
    file: Blob | File;
  };
  path?: never;
  query?: never;
  url: "/users/me/avatar";
};

export type EditUserAvatarErrors = {
  /**
   * Invalid Multipart payload.
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * No file uploaded.
   */
  404: DefaultError;
  /**
   * Payload Too Large
   */
  413: DefaultError;
  /**
   * Too many requests.
   */
  429: DefaultError;
  /**
   * Unknown error.
   */
  500: DefaultError;
};

export type EditUserAvatarError =
  EditUserAvatarErrors[keyof EditUserAvatarErrors];

export type EditUserAvatarResponses = {
  /**
   * Avatar updated successfuly
   */
  200: {
    /**
     * Uploaded avatar hash.
     */
    hash: string;
  };
};

export type EditUserAvatarResponse =
  EditUserAvatarResponses[keyof EditUserAvatarResponses];

export type GetUserData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/users/me";
};

export type GetUserErrors = {
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * Too many requests.
   */
  429: DefaultError;
  /**
   * Unknown error.
   */
  500: DefaultError;
};

export type GetUserError = GetUserErrors[keyof GetUserErrors];

export type GetUserResponses = {
  /**
   * Successful response
   */
  200: {
    /**
     * User ID.
     */
    id: number;
    /**
     * Public user name.
     */
    name: string;
    /**
     * User email.
     */
    email?: string;
    /**
     * User avatar hash.
     */
    avatar?: string;
    /**
     * Configured webhook URL.
     */
    webhook?: string;
    /**
     * User timezone.
     */
    timezone?: string;
    /**
     * User creation timestamp.
     */
    joinedAt: number;
    payment: {
      entities: {
        efi: {
          id?: string;
          /**
           * Configured Pix key.
           */
          pixKey?: string;
          settings?: null | {
            fee?: number;
            hoursToReceive?: number;
          };
        };
        mercadopago: {
          id?: string;
          /**
           * Configured Pix key.
           */
          pixKey?: string;
          settings?: null | {
            fee?: number;
            hoursToReceive?: number;
          };
        };
        semiauto: {
          id?: string;
          /**
           * Configured Pix key.
           */
          pixKey?: string;
          settings?: null | {
            fee?: number;
            hoursToReceive?: number;
          };
        };
        "wallet-efi": {
          id?: string;
          /**
           * Configured Pix key.
           */
          pixKey?: string;
          settings?: null | {
            fee?: number;
            hoursToReceive?: number;
          };
        };
      };
      preferences: {
        pix: null | "mercadopago" | "efi" | "semiauto" | "wallet-efi";
      };
    };
    connections: {
      discord?: null | string;
    };
    legal: {
      status?: null | "pending" | "approved" | "rejected";
      type?: "cpf" | "cnpj";
      rejectedReason?: string;
    };
  };
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type EditUserData = {
  body?: {
    /**
     * Public name. Must be 3 to 50 valid characters.
     */
    name: string;
  };
  path?: never;
  query?: never;
  url: "/users/me";
};

export type EditUserErrors = {
  /**
   * Invalid JSON payload.
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * Payload too large.
   */
  413: DefaultError;
  /**
   * Invalid name.
   */
  422: DefaultError;
  /**
   * Unknown error.
   */
  500: DefaultError;
};

export type EditUserError = EditUserErrors[keyof EditUserErrors];

export type EditUserResponses = {
  /**
   * User modified succesfully
   */
  204: void;
};

export type EditUserResponse = EditUserResponses[keyof EditUserResponses];

export type EditUserPaymentMethodData = {
  body?: {
    pix: null | string;
  };
  path?: never;
  query?: never;
  url: "/users/me/payment-method";
};

export type EditUserPaymentMethodErrors = {
  /**
   * Invalid JSON payload.
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * Payload too large.
   */
  413: DefaultError;
  /**
   * Invalid payment method.
   */
  422: DefaultError;
  /**
   * Too many requests.
   */
  429: DefaultError;
  /**
   * Unknown error.
   */
  500: DefaultError;
};

export type EditUserPaymentMethodError =
  EditUserPaymentMethodErrors[keyof EditUserPaymentMethodErrors];

export type EditUserPaymentMethodResponses = {
  /**
   * Payment method updated.
   */
  204: void;
};

export type EditUserPaymentMethodResponse =
  EditUserPaymentMethodResponses[keyof EditUserPaymentMethodResponses];

export type SetupEfiData = {
  body?: {
    certificate: Blob | File;
    pix_key: string;
    client_id: string;
    client_secret: string;
  };
  path?: never;
  query?: never;
  url: "/users/me/payments/efi/setup";
};

export type SetupEfiErrors = {
  /**
   * Bad Request
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * Forbidden
   */
  403: DefaultError;
  /**
   * Invalid certificate.
   */
  415: DefaultError;
  /**
   * Unprocessable Entity
   */
  422: DefaultError;
  /**
   * Too many requests.
   */
  429: DefaultError;
  /**
   * Internal Server Error
   */
  500: DefaultError;
};

export type SetupEfiError = SetupEfiErrors[keyof SetupEfiErrors];

export type SetupEfiResponses = {
  /**
   * Efí integration configured. Returns account ID
   */
  200: {
    /**
     * Efí account ID.
     */
    id: string;
  };
};

export type SetupEfiResponse = SetupEfiResponses[keyof SetupEfiResponses];

export type SetupSemiautoData = {
  body?: {
    /**
     * Pix key.
     */
    pix_key: string;
  };
  path?: never;
  query?: never;
  url: "/users/me/payments/semiauto";
};

export type SetupSemiautoErrors = {
  /**
   * Invalid JSON payload.
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * Payload too large.
   */
  413: DefaultError;
  /**
   * Unprocessable Entity
   */
  422: DefaultError;
  /**
   * Too many requests.
   */
  429: DefaultError;
  /**
   * Unknown error.
   */
  500: DefaultError;
};

export type SetupSemiautoError = SetupSemiautoErrors[keyof SetupSemiautoErrors];

export type SetupSemiautoResponses = {
  /**
   * Semiauto configured succesfully.
   */
  204: void;
};

export type SetupSemiautoResponse =
  SetupSemiautoResponses[keyof SetupSemiautoResponses];

export type WalletBalanceData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/users/me/wallet/balance";
};

export type WalletBalanceErrors = {
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * Too many requests.
   */
  429: DefaultError;
  /**
   * Unknown error.
   */
  500: DefaultError;
};

export type WalletBalanceError = WalletBalanceErrors[keyof WalletBalanceErrors];

export type WalletBalanceResponses = {
  /**
   * Balance returned successfully.
   */
  200: {
    /**
     * Legacy balance under the old withdrawal-fee rules.
     */
    old: number;
    /**
     * Pending wallet balance.
     */
    pending: number;
    /**
     * Available wallet balance.
     */
    available: number;
    /**
     * Balance held while a Pix dispute (MED) is under analysis.
     */
    analysis: number;
    /**
     * Hourly release schedule of the pending balance; sums to `pending`.
     */
    schedule: Array<{
      /**
       * Unix ms timestamp of the :00 boundary when this slice becomes available.
       */
      at: number;
      /**
       * Net BRL amount that leaves 'pending' at this boundary.
       */
      value: number;
    }>;
  };
};

export type WalletBalanceResponse =
  WalletBalanceResponses[keyof WalletBalanceResponses];

export type ListStoresData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/stores";
};

export type ListStoresErrors = {
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * Too many requests.
   */
  429: DefaultError;
  /**
   * Unknown error.
   */
  500: DefaultError;
};

export type ListStoresError = ListStoresErrors[keyof ListStoresErrors];

export type ListStoresResponses = {
  /**
   * Stores listed successfully.
   */
  200: Array<{
    id: number;
    name: string;
    created_at: number;
    expires_at: number;
    icon_id: null | string;
    banner_id: null | string;
    is_owner: boolean;
    color: number;
  }>;
};

export type ListStoresResponse = ListStoresResponses[keyof ListStoresResponses];

export type RateTransactionData = {
  body?: {
    /**
     * Rating message.
     */
    message?: string;
    /**
     * Rating stars.
     */
    stars: number;
  };
  path: {
    transactionId: string;
  };
  query?: never;
  url: "/transactions/{transactionId}/rating";
};

export type RateTransactionErrors = {
  /**
   * Invalid JSON payload.
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * Transaction not found.
   */
  404: DefaultError;
  /**
   * Payload too large.
   */
  413: DefaultError;
  /**
   * Unprocessable Entity
   */
  422: DefaultError;
  /**
   * Too many requests.
   */
  429: DefaultError;
  /**
   * Unknown error.
   */
  500: DefaultError;
};

export type RateTransactionError =
  RateTransactionErrors[keyof RateTransactionErrors];

export type RateTransactionResponses = {
  /**
   * Transaction rated successfully.
   */
  200: {
    id: string;
    /**
     * Represents the enum public.transaction_type
     */
    type: "sale" | "transfer" | "deposit" | "withdraw";
    /**
     * Represents the enum public.payment_entity
     */
    entity: "mercadopago" | "efi" | "semiauto" | "wallet-efi";
    /**
     * Represents the enum public.payment_method
     */
    method: "pix" | "boleto";
    /**
     * Represents the enum public.transaction_status
     */
    status:
      | "pending"
      | "approved"
      | "expired"
      | "cancelled"
      | "refused"
      | "refunded"
      | "analysis"
      | "invalid-pix-key";
    base_value: number;
    value: number;
    refunded_value: number;
    refund_reason:
      | null
      | "fraud"
      | "pix_med"
      | "requested_with_zennify"
      | "requested_with_bank"
      | "stock_out"
      | "stock_low"
      | "by_admin"
      | "internal_error"
      | "internal_reason"
      | "bank_blacklist"
      | "bank_rejected"
      | "coupon_out";
    refund_comment: null | string;
    refund_requested_by: null | number;
    payer_bank: null | string;
    ref_code: null | string;
    expires_at: null | number;
    created_at: number;
    managed: null | boolean;
    pix_e2eid: null | string;
    pix_qrcode: null | string;
    metadata: unknown;
    order: null | {
      id: string;
      total_value: number;
      coupon_id: null | number;
      subtotal: number;
      discount: number;
      /**
       * Represents the enum public.platforms
       */
      platform: "discord" | "website" | "marketplace" | "whatsapp" | "telegram";
      discord_guild_id: null | string;
      discord_channel_id: null | string;
      discord_channel_message_id: null | string;
      discord_sale_message: null | string;
      discord_feedback_message: null | string;
      rating: null | number;
      rating_message: null | string;
      coupon_name: null | string;
      /**
       * From T, pick a set of properties whose keys are in the union K
       */
      payer: {
        id: number;
        discord_user_id: null | string;
        username: string;
      };
      /**
       * From T, pick a set of properties whose keys are in the union K
       */
      seller: {
        id: number;
        discord_user_id: null | string;
        username: string;
      };
      /**
       * From T, pick a set of properties whose keys are in the union K
       */
      store: {
        id: number;
        name: string;
        icon_id: null | string;
        banner_id: null | string;
      };
      products: null | Array<{
        id: number;
        value: number;
        name: string;
        icon_id: null | string;
        banner_id: null | string;
        short_description: null | string;
        discord_description: null | string;
        website_description: null | string;
        instructions: null | string;
        amount: number;
        delivered: Array<string>;
      }>;
      discord_roles: null | Array<{
        id: number;
        user_id: number;
        guild_id: string;
        role_id: string;
        rule_id: null | number;
        role_name: null | string;
        role_color_primary: null | number;
        role_color_secondary: null | number;
        remove_in: null | number;
        should_add: boolean;
        given: null | boolean;
        discord_user_id: null | string;
      }>;
    };
    withdraw: null | {
      total_value: number;
      sended_pix_key: null | string;
      fee: number;
      subtotal: number;
      discount: number;
    };
  };
};

export type RateTransactionResponse =
  RateTransactionResponses[keyof RateTransactionResponses];

export type RefundTransactionData = {
  body?: {
    /**
     * Refund amount. Omit to refund the remaining value.
     */
    value?: number;
    /**
     * Refund comment shown in the transaction history.
     */
    comment?: string;
  };
  path: {
    transactionId: string;
  };
  query?: never;
  url: "/transactions/{transactionId}/refund";
};

export type RefundTransactionErrors = {
  /**
   * Invalid JSON payload.
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * Refund not allowed.
   */
  403: DefaultError;
  /**
   * Transaction not found.
   */
  404: DefaultError;
  /**
   * Conflict
   */
  409: DefaultError;
  /**
   * Payload too large.
   */
  413: DefaultError;
  /**
   * Unprocessable Entity
   */
  422: DefaultError;
  /**
   * Too many requests.
   */
  429: DefaultError;
  /**
   * Internal Server Error
   */
  500: DefaultError;
};

export type RefundTransactionError =
  RefundTransactionErrors[keyof RefundTransactionErrors];

export type RefundTransactionResponses = {
  /**
   * Refund accepted.
   */
  202: unknown;
};

export type ListTransactionsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Transaction id or Pix E2E id.
     */
    q?: string;
    /**
     * Maximum creation date.
     */
    before?: string;
    /**
     * Transaction status filter.
     */
    status?: string;
    /**
     * Transaction value filter.
     */
    value?: string;
    /**
     * Transaction type filter.
     */
    type?: string;
    /**
     * Maximum number of transactions.
     */
    limit?: string;
    /**
     * User id or Discord user id filter.
     */
    user?: string;
  };
  url: "/transactions";
};

export type ListTransactionsErrors = {
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * Too many requests.
   */
  429: DefaultError;
  /**
   * Unknown error.
   */
  500: DefaultError;
};

export type ListTransactionsError =
  ListTransactionsErrors[keyof ListTransactionsErrors];

export type ListTransactionsResponses = {
  /**
   * Transactions listed successfully.
   */
  200: Array<{
    id: string;
    /**
     * Represents the enum public.transaction_type
     */
    type: "sale" | "transfer" | "deposit" | "withdraw";
    /**
     * Represents the enum public.transaction_status
     */
    status:
      | "pending"
      | "approved"
      | "expired"
      | "cancelled"
      | "refused"
      | "refunded"
      | "analysis"
      | "invalid-pix-key";
    base_value: number;
    value: number;
    created_at: number;
    primaryUser: boolean;
  }>;
};

export type ListTransactionsResponse =
  ListTransactionsResponses[keyof ListTransactionsResponses];

export type WalletWithdrawData = {
  body?: {
    /**
     * Money value.
     */
    value: number;
    automatic: boolean;
  };
  path?: never;
  query?: never;
  url: "/users/me/wallet/withdraw";
};

export type WalletWithdrawErrors = {
  /**
   * Invalid JSON payload.
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * Conflict
   */
  409: DefaultError;
  /**
   * Payload too large.
   */
  413: DefaultError;
  /**
   * Invalid parameter.
   */
  422: DefaultError;
  /**
   * Too Many Requests
   */
  429: DefaultError;
  /**
   * Unknown error.
   */
  500: DefaultError;
};

export type WalletWithdrawError =
  WalletWithdrawErrors[keyof WalletWithdrawErrors];

export type WalletWithdrawResponses = {
  /**
   * Withdraw requested succesfully.
   */
  200: {
    /**
     * Withdraw transaction ID.
     */
    id: string;
  };
};

export type WalletWithdrawResponse =
  WalletWithdrawResponses[keyof WalletWithdrawResponses];

export type GetProductHistoryData = {
  body?: never;
  path: {
    storeId: string;
    productId: string;
  };
  query?: {
    /**
     * Delivery time cursor in ms; only records strictly before are returned.
     */
    before?: string;
    /**
     * Number of history entries (max 50, default 20).
     */
    limit?: string;
    type?: "sale" | "deliver";
    /**
     * Filter by recipient user (users.core.id, discord_user_id or email).
     */
    to?: string;
    /**
     * Filter by moderator who ran /produtos entregar (users.core.id, discord_user_id or email). Ignored when type=sale.
     */
    by?: string;
  };
  url: "/stores/{storeId}/products/{productId}/history";
};

export type GetProductHistoryErrors = {
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Unknown store.
   */
  404: DefaultError;
  /**
   * Unknown error.
   */
  500: DefaultError;
};

export type GetProductHistoryError =
  GetProductHistoryErrors[keyof GetProductHistoryErrors];

export type GetProductHistoryResponses = {
  /**
   * History entries returned in descending order by delivery time.
   */
  200: Array<
    | {
        /**
         * Transaction id (transactions.core) or deliver id serialized as string.
         */
        id: string;
        /**
         * Delivery timestamp in ms.
         */
        at: number;
        to: {
          id: number;
          username: string;
          avatar: null | string;
        };
        items: Array<{
          id: number;
          content: string;
          cost: null | number;
          value: null | number;
        }>;
        type: "sale";
        order: {
          total_value: number;
          /**
           * How many stock rows the buyer paid for. items.length may be lower on partial delivery.
           */
          amount_expected: number;
          /**
           * Represents the enum public.transaction_status
           */
          status:
            | "pending"
            | "approved"
            | "expired"
            | "cancelled"
            | "refused"
            | "refunded"
            | "analysis"
            | "invalid-pix-key";
          refunded_value: number;
        };
      }
    | {
        /**
         * Transaction id (transactions.core) or deliver id serialized as string.
         */
        id: string;
        /**
         * Delivery timestamp in ms.
         */
        at: number;
        to: {
          id: number;
          username: string;
          avatar: null | string;
        };
        items: Array<{
          id: number;
          content: string;
          cost: null | number;
          value: null | number;
        }>;
        type: "deliver";
        by: {
          id: number;
          username: string;
          avatar: null | string;
        };
      }
  >;
};

export type GetProductHistoryResponse =
  GetProductHistoryResponses[keyof GetProductHistoryResponses];

export type SendProductDiscordMessageData = {
  body?: {
    /**
     * Discord channel id where the product message should be posted.
     */
    channel_id: string;
  };
  path: {
    storeId: string;
    productId: string;
  };
  query?: never;
  url: "/stores/{storeId}/products/{productId}/discord_messages";
};

export type SendProductDiscordMessageErrors = {
  /**
   * Invalid JSON payload.
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Not Found
   */
  404: DefaultError;
  /**
   * Payload too large.
   */
  413: DefaultError;
  /**
   * Unknown channel.
   */
  422: DefaultError;
  /**
   * Unknown error.
   */
  500: DefaultError;
};

export type SendProductDiscordMessageError =
  SendProductDiscordMessageErrors[keyof SendProductDiscordMessageErrors];

export type SendProductDiscordMessageResponses = {
  /**
   * Discord product message queued successfully.
   */
  202: unknown;
};

export type DeleteProductData = {
  body?: never;
  path: {
    storeId: string;
    productId: string;
  };
  query?: never;
  url: "/stores/{storeId}/products/{productId}";
};

export type DeleteProductErrors = {
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Unknown store.
   */
  404: DefaultError;
  /**
   * Unknown error.
   */
  500: DefaultError;
};

export type DeleteProductError = DeleteProductErrors[keyof DeleteProductErrors];

export type DeleteProductResponses = {
  /**
   * Product deleted successfully.
   */
  204: void;
};

export type DeleteProductResponse =
  DeleteProductResponses[keyof DeleteProductResponses];

export type GetProductData = {
  body?: never;
  path: {
    storeId: string;
    productId: string;
  };
  query?: never;
  url: "/stores/{storeId}/products/{productId}";
};

export type GetProductErrors = {
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Unknown store.
   */
  404: DefaultError;
  /**
   * Unknown error.
   */
  500: DefaultError;
};

export type GetProductError = GetProductErrors[keyof GetProductErrors];

export type GetProductResponses = {
  /**
   * Product returned successfully.
   */
  200: {
    id: number;
    name: string;
    value: number;
    icon_id: null | string;
    banner_id: null | string;
    owner_id: number;
    store_id: number;
    created_at: number;
    stock: {
      size: number;
      locked: boolean;
      /**
       * Represents the enum products.stock_mode
       */
      mode: "random" | "sequential";
      limit: number;
    };
    description: {
      discord: string;
      short: string;
      website: string;
    };
    instructions: string;
    color: null | number;
    discord_roles_allowed: Array<string>;
    discord_roles_blocked: Array<string>;
  };
};

export type GetProductResponse = GetProductResponses[keyof GetProductResponses];

export type EditProductData = {
  body?: {
    /**
     * Public name. Must be 3 to 50 valid characters.
     */
    name?: string;
    /**
     * Product price in BRL.
     */
    value?: number;
    description?: {
      /**
       * Product description used in Discord messages.
       */
      discord?: string;
    };
    /**
     * How to use the delivered stock. Sent to the buyer with the delivery. Empty string clears it.
     */
    instructions?: string;
    color?: null | number;
    /**
     * Discord role ids allowed to buy this product. The buyer needs at least one of them, and up to 25 are accepted. An empty list lets anyone buy.
     */
    discord_roles_allowed?: Array<string>;
    /**
     * Discord role ids blocked from buying this product. Blocked wins over allowed, and up to 25 are accepted. An empty list blocks nobody.
     */
    discord_roles_blocked?: Array<string>;
  };
  path: {
    storeId: string;
    productId: string;
  };
  query?: never;
  url: "/stores/{storeId}/products/{productId}";
};

export type EditProductErrors = {
  /**
   * Invalid JSON payload.
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Unknown store.
   */
  404: DefaultError;
  /**
   * Payload too large.
   */
  413: DefaultError;
  /**
   * Unprocessable Entity
   */
  422: DefaultError;
  /**
   * Unknown error.
   */
  500: DefaultError;
};

export type EditProductError = EditProductErrors[keyof EditProductErrors];

export type EditProductResponses = {
  /**
   * Product updated successfully.
   */
  204: void;
};

export type EditProductResponse =
  EditProductResponses[keyof EditProductResponses];

export type ListProductsData = {
  body?: never;
  path: {
    storeId: string;
  };
  query?: never;
  url: "/stores/{storeId}/products";
};

export type ListProductsErrors = {
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Unknown store.
   */
  404: DefaultError;
  /**
   * Unknown error.
   */
  500: DefaultError;
};

export type ListProductsError = ListProductsErrors[keyof ListProductsErrors];

export type ListProductsResponses = {
  /**
   * Products listed successfully.
   */
  200: Array<{
    id: number;
    name: string;
    icon_id: null | string;
    banner_id: null | string;
    value: number;
    stock_locked: null | boolean;
    stock_count: number;
  }>;
};

export type ListProductsResponse =
  ListProductsResponses[keyof ListProductsResponses];

export type CreateProductData = {
  body?: {
    /**
     * Public name. Must be 3 to 50 valid characters.
     */
    name: string;
    /**
     * Product price in BRL.
     */
    value: number;
  };
  path: {
    storeId: string;
  };
  query?: never;
  url: "/stores/{storeId}/products";
};

export type CreateProductErrors = {
  /**
   * Invalid JSON payload.
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Unknown store.
   */
  404: DefaultError;
  /**
   * Payload too large.
   */
  413: DefaultError;
  /**
   * Unprocessable Entity
   */
  422: DefaultError;
  /**
   * Unknown error.
   */
  500: DefaultError;
};

export type CreateProductError = CreateProductErrors[keyof CreateProductErrors];

export type CreateProductResponses = {
  /**
   * Product created successfully.
   */
  200: {
    /**
     * Product ID.
     */
    id: number;
  };
};

export type CreateProductResponse =
  CreateProductResponses[keyof CreateProductResponses];

export type EditProductStockItemData = {
  body?: {
    /**
     * Private stock content delivered to the buyer.
     */
    content?: string;
    /**
     * Internal cost for this stock item.
     */
    cost?: number;
  };
  path: {
    storeId: string;
    productId: string;
    stockId: string;
  };
  query?: never;
  url: "/stores/{storeId}/products/{productId}/stock/{stockId}";
};

export type EditProductStockItemErrors = {
  /**
   * Invalid JSON payload.
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Forbidden
   */
  403: DefaultError;
  /**
   * Not Found
   */
  404: DefaultError;
  /**
   * Payload too large.
   */
  413: DefaultError;
  /**
   * Unprocessable Entity
   */
  422: DefaultError;
  /**
   * Unknown error.
   */
  500: DefaultError;
};

export type EditProductStockItemError =
  EditProductStockItemErrors[keyof EditProductStockItemErrors];

export type EditProductStockItemResponses = {
  /**
   * Stock item updated successfully.
   */
  204: void;
};

export type EditProductStockItemResponse =
  EditProductStockItemResponses[keyof EditProductStockItemResponses];

export type GetProductStockData = {
  body?: never;
  path: {
    storeId: string;
    productId: string;
  };
  query?: never;
  url: "/stores/{storeId}/products/{productId}/stock";
};

export type GetProductStockErrors = {
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Unknown store.
   */
  404: DefaultError;
  /**
   * Too many requests.
   */
  429: DefaultError;
  /**
   * Unknown error.
   */
  500: DefaultError;
};

export type GetProductStockError =
  GetProductStockErrors[keyof GetProductStockErrors];

export type GetProductStockResponses = {
  /**
   * Stock items listed successfully.
   */
  200: Array<{
    /**
     * Stock item ID.
     */
    id: number;
    /**
     * Private stock content delivered to the buyer.
     */
    content: string;
    /**
     * Internal cost for this stock item.
     */
    cost: number;
  }>;
};

export type GetProductStockResponse =
  GetProductStockResponses[keyof GetProductStockResponses];

export type EditProductStockData = {
  body?: {
    stock_locked?: boolean;
    stock_mode?: "random" | "sequential";
    add?: Array<{
      /**
       * Private stock content delivered to the buyer.
       */
      content: string;
      /**
       * Internal cost for this stock item.
       */
      cost: number;
      id?: number;
    }>;
    remove?: Array<number>;
  };
  path: {
    storeId: string;
    productId: string;
  };
  query?: never;
  url: "/stores/{storeId}/products/{productId}/stock";
};

export type EditProductStockErrors = {
  /**
   * Invalid JSON payload.
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Forbidden
   */
  403: DefaultError;
  /**
   * Unknown store.
   */
  404: DefaultError;
  /**
   * Payload too large.
   */
  413: DefaultError;
  /**
   * Unprocessable Entity
   */
  422: DefaultError;
  /**
   * Too many requests.
   */
  429: DefaultError;
  /**
   * Unknown error.
   */
  500: DefaultError;
};

export type EditProductStockError =
  EditProductStockErrors[keyof EditProductStockErrors];

export type EditProductStockResponses = {
  /**
   * Product stock updated successfully.
   */
  200: {
    stock_locked: boolean;
    stock_mode: "random" | "sequential";
    /**
     * Available stock items after the change.
     */
    stock_count: number;
    added_ids: Array<number>;
  };
};

export type EditProductStockResponse =
  EditProductStockResponses[keyof EditProductStockResponses];

export type EditDiscordAppAutoCrosspostData = {
  body?: {
    enabled?: boolean;
    general?: boolean;
    tips_enabled?: boolean;
    channels_whitelist?: Array<string>;
    channels_blacklist?: Array<string>;
  };
  path: {
    storeId: string;
  };
  query?: never;
  url: "/stores/{storeId}/app/discord/auto/crosspost";
};

export type EditDiscordAppAutoCrosspostErrors = {
  /**
   * Invalid JSON payload.
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Unknown store.
   */
  404: DefaultError;
  /**
   * Payload too large.
   */
  413: DefaultError;
  /**
   * Invalid Discord channel.
   */
  422: DefaultError;
  /**
   * Unknown error.
   */
  500: DefaultError;
};

export type EditDiscordAppAutoCrosspostError =
  EditDiscordAppAutoCrosspostErrors[keyof EditDiscordAppAutoCrosspostErrors];

export type EditDiscordAppAutoCrosspostResponses = {
  /**
   * Auto crosspost configuration updated successfully.
   */
  204: void;
};

export type EditDiscordAppAutoCrosspostResponse =
  EditDiscordAppAutoCrosspostResponses[keyof EditDiscordAppAutoCrosspostResponses];

export type DeleteDiscordAppAutoReactData = {
  body?: {
    /**
     * Discord snowflake id.
     */
    guild_id: string;
    /**
     * Discord snowflake id, or the '@feedback' sentinel for the store feedback channel.
     */
    channel_id: string;
  };
  path: {
    storeId: string;
  };
  query?: never;
  url: "/stores/{storeId}/app/discord/auto/react";
};

export type DeleteDiscordAppAutoReactErrors = {
  /**
   * Invalid JSON payload.
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Not Found
   */
  404: DefaultError;
  /**
   * Payload too large.
   */
  413: DefaultError;
  /**
   * Invalid Discord id.
   */
  422: DefaultError;
  /**
   * Unknown error.
   */
  500: DefaultError;
};

export type DeleteDiscordAppAutoReactError =
  DeleteDiscordAppAutoReactErrors[keyof DeleteDiscordAppAutoReactErrors];

export type DeleteDiscordAppAutoReactResponses = {
  /**
   * Auto react configuration deleted.
   */
  204: void;
};

export type DeleteDiscordAppAutoReactResponse =
  DeleteDiscordAppAutoReactResponses[keyof DeleteDiscordAppAutoReactResponses];

export type EditDiscordAppAutoReactData = {
  body?: {
    /**
     * Discord snowflake id.
     */
    guild_id: string;
    /**
     * Discord snowflake id, or the '@feedback' sentinel for the store feedback channel.
     */
    channel_id: string;
    enabled?: boolean;
    emojis?: Array<string>;
    mode?: "random" | "all";
    random_count?: number;
    ignore_bots?: boolean;
  };
  path: {
    storeId: string;
  };
  query?: never;
  url: "/stores/{storeId}/app/discord/auto/react";
};

export type EditDiscordAppAutoReactErrors = {
  /**
   * Invalid JSON payload.
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Not Found
   */
  404: DefaultError;
  /**
   * Payload too large.
   */
  413: DefaultError;
  /**
   * Unprocessable Entity
   */
  422: DefaultError;
  /**
   * Unknown error.
   */
  500: DefaultError;
};

export type EditDiscordAppAutoReactError =
  EditDiscordAppAutoReactErrors[keyof EditDiscordAppAutoReactErrors];

export type EditDiscordAppAutoReactResponses = {
  /**
   * Auto react configuration updated.
   */
  204: void;
};

export type EditDiscordAppAutoReactResponse =
  EditDiscordAppAutoReactResponses[keyof EditDiscordAppAutoReactResponses];

export type CreateDiscordAppAutoReactData = {
  body?: {
    /**
     * Discord snowflake id.
     */
    guild_id: string;
    /**
     * Discord snowflake id, or the '@feedback' sentinel for the store feedback channel.
     */
    channel_id: string;
    enabled?: boolean;
    emojis?: Array<string>;
    mode?: "random" | "all";
    random_count?: number;
    ignore_bots?: boolean;
  };
  path: {
    storeId: string;
  };
  query?: never;
  url: "/stores/{storeId}/app/discord/auto/react";
};

export type CreateDiscordAppAutoReactErrors = {
  /**
   * Invalid JSON payload.
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Forbidden
   */
  403: DefaultError;
  /**
   * Unknown store.
   */
  404: DefaultError;
  /**
   * Auto react already configured.
   */
  409: DefaultError;
  /**
   * Payload too large.
   */
  413: DefaultError;
  /**
   * Unprocessable Entity
   */
  422: DefaultError;
  /**
   * Unknown error.
   */
  500: DefaultError;
};

export type CreateDiscordAppAutoReactError =
  CreateDiscordAppAutoReactErrors[keyof CreateDiscordAppAutoReactErrors];

export type CreateDiscordAppAutoReactResponses = {
  /**
   * Auto react configuration created.
   */
  204: void;
};

export type CreateDiscordAppAutoReactResponse =
  CreateDiscordAppAutoReactResponses[keyof CreateDiscordAppAutoReactResponses];

export type CreateDiscordAppAutoRoleData = {
  body?: {
    /**
     * Discord snowflake id.
     */
    role_id: string;
    /**
     * Represents the enum discord.auto_role_trigger
     */
    trigger:
      | "buy"
      | "rankingPosition"
      | "rankingMoney"
      | "rankingCount"
      | "guildEnter";
    only_products: Array<number>;
    meta: null | number;
    ttl: null | number;
    only_discord: null | boolean;
    /**
     * Discord snowflake id.
     */
    guild_id: string;
  };
  path: {
    storeId: string;
  };
  query?: never;
  url: "/stores/{storeId}/app/discord/auto/roles";
};

export type CreateDiscordAppAutoRoleErrors = {
  /**
   * Invalid JSON payload.
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Forbidden
   */
  403: DefaultError;
  /**
   * Unknown store.
   */
  404: DefaultError;
  /**
   * Payload too large.
   */
  413: DefaultError;
  /**
   * Unprocessable Entity
   */
  422: DefaultError;
  /**
   * Unknown error.
   */
  500: DefaultError;
};

export type CreateDiscordAppAutoRoleError =
  CreateDiscordAppAutoRoleErrors[keyof CreateDiscordAppAutoRoleErrors];

export type CreateDiscordAppAutoRoleResponses = {
  /**
   * Auto role rule created.
   */
  200: {
    id: number;
    guild_id: string;
    role_id: string;
    /**
     * Represents the enum discord.auto_role_trigger
     */
    trigger:
      | "buy"
      | "rankingPosition"
      | "rankingMoney"
      | "rankingCount"
      | "guildEnter";
    only_products: Array<number>;
    meta: null | number;
    ttl: null | number;
    only_discord: null | boolean;
    legacy: boolean;
  };
};

export type CreateDiscordAppAutoRoleResponse =
  CreateDiscordAppAutoRoleResponses[keyof CreateDiscordAppAutoRoleResponses];

export type DeleteDiscordAppAutoRoleData = {
  body?: never;
  path: {
    storeId: string;
    ruleId: string;
  };
  query?: never;
  url: "/stores/{storeId}/app/discord/auto/roles/{ruleId}";
};

export type DeleteDiscordAppAutoRoleErrors = {
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Not Found
   */
  404: DefaultError;
  /**
   * Unknown error.
   */
  500: DefaultError;
};

export type DeleteDiscordAppAutoRoleError =
  DeleteDiscordAppAutoRoleErrors[keyof DeleteDiscordAppAutoRoleErrors];

export type DeleteDiscordAppAutoRoleResponses = {
  /**
   * Auto role rule deleted.
   */
  204: void;
};

export type DeleteDiscordAppAutoRoleResponse =
  DeleteDiscordAppAutoRoleResponses[keyof DeleteDiscordAppAutoRoleResponses];

export type EditDiscordAppAutoRoleData = {
  /**
   * Make all properties in T optional
   */
  body?: {
    /**
     * Discord snowflake id.
     */
    role_id?: string;
    trigger?:
      | "buy"
      | "rankingPosition"
      | "rankingMoney"
      | "rankingCount"
      | "guildEnter";
    only_products?: Array<number>;
    meta?: null | number;
    ttl?: null | number;
    only_discord?: null | boolean;
  };
  path: {
    storeId: string;
    ruleId: string;
  };
  query?: never;
  url: "/stores/{storeId}/app/discord/auto/roles/{ruleId}";
};

export type EditDiscordAppAutoRoleErrors = {
  /**
   * Invalid JSON payload.
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Not Found
   */
  404: DefaultError;
  /**
   * Payload too large.
   */
  413: DefaultError;
  /**
   * Unprocessable Entity
   */
  422: DefaultError;
  /**
   * Unknown error.
   */
  500: DefaultError;
};

export type EditDiscordAppAutoRoleError =
  EditDiscordAppAutoRoleErrors[keyof EditDiscordAppAutoRoleErrors];

export type EditDiscordAppAutoRoleResponses = {
  /**
   * Auto role rule updated.
   */
  204: void;
};

export type EditDiscordAppAutoRoleResponse =
  EditDiscordAppAutoRoleResponses[keyof EditDiscordAppAutoRoleResponses];

export type EditDiscordAppChannelsData = {
  body?: {
    /**
     * Discord guild and channel binding.
     */
    carts?: {
      /**
       * Discord guild id.
       */
      guild_id: string;
      channel_id?: null | string;
    };
    /**
     * Discord guild and channel binding.
     */
    feedbacks?: {
      /**
       * Discord guild id.
       */
      guild_id: string;
      channel_id?: null | string;
    };
    /**
     * Discord guild and channel binding.
     */
    sales?: {
      /**
       * Discord guild id.
       */
      guild_id: string;
      channel_id?: null | string;
    };
    /**
     * Discord guild and channel binding.
     */
    voice?: {
      /**
       * Discord guild id.
       */
      guild_id: string;
      channel_id?: null | string;
    };
  };
  path: {
    storeId: string;
  };
  query?: never;
  url: "/stores/{storeId}/app/discord/channels";
};

export type EditDiscordAppChannelsErrors = {
  /**
   * Invalid JSON payload.
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Unknown store.
   */
  404: DefaultError;
  /**
   * Payload too large.
   */
  413: DefaultError;
  /**
   * Unprocessable Entity
   */
  422: DefaultError;
  /**
   * Unknown error.
   */
  500: DefaultError;
};

export type EditDiscordAppChannelsError =
  EditDiscordAppChannelsErrors[keyof EditDiscordAppChannelsErrors];

export type EditDiscordAppChannelsResponses = {
  /**
   * Discord channels updated successfully.
   */
  204: void;
};

export type EditDiscordAppChannelsResponse =
  EditDiscordAppChannelsResponses[keyof EditDiscordAppChannelsResponses];

export type GetDiscordAppEmojisData = {
  body?: never;
  path: {
    storeId: string;
  };
  query?: never;
  url: "/stores/{storeId}/app/discord/emojis";
};

export type GetDiscordAppEmojisErrors = {
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Unknown store.
   */
  404: DefaultError;
  /**
   * Unknown error.
   */
  500: DefaultError;
};

export type GetDiscordAppEmojisError =
  GetDiscordAppEmojisErrors[keyof GetDiscordAppEmojisErrors];

export type GetDiscordAppEmojisResponses = {
  200: {
    [key: string]: {
      name: string;
      guild?: string;
      anim?: boolean;
    };
  };
};

export type GetDiscordAppEmojisResponse =
  GetDiscordAppEmojisResponses[keyof GetDiscordAppEmojisResponses];

export type GetDiscordAppInfoData = {
  body?: never;
  path: {
    storeId: string;
  };
  query?: never;
  url: "/stores/{storeId}/app/discord";
};

export type GetDiscordAppInfoErrors = {
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Unknown store.
   */
  404: DefaultError;
  /**
   * Unknown error.
   */
  500: DefaultError;
};

export type GetDiscordAppInfoError =
  GetDiscordAppInfoErrors[keyof GetDiscordAppInfoErrors];

export type GetDiscordAppInfoResponses = {
  /**
   * Discord app info returned successfully.
   */
  200:
    | {
        valid: false;
      }
    | {
        valid: true;
        /**
         * Discord bot id.
         */
        id: string;
        /**
         * Discord bot username.
         */
        username: string;
        avatar: null | string;
        /**
         * Discord bot discriminator.
         */
        discriminator: string;
        banner: null | string;
        /**
         * Discord bot bio.
         */
        bio: string;
        guilds: Array<{
          /**
           * Discord guild id.
           */
          id: string;
          /**
           * Discord guild name.
           */
          name: string;
          icon: null | string;
          banner: boolean;
          hasAdmin: boolean;
          /**
           * Approximate guild member count.
           */
          members: number;
        }>;
      };
};

export type GetDiscordAppInfoResponse =
  GetDiscordAppInfoResponses[keyof GetDiscordAppInfoResponses];

export type GetDiscordAppRolesData = {
  body?: never;
  path: {
    storeId: string;
  };
  query?: never;
  url: "/stores/{storeId}/app/discord/roles";
};

export type GetDiscordAppRolesErrors = {
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Unknown store.
   */
  404: DefaultError;
  /**
   * Unknown error.
   */
  500: DefaultError;
};

export type GetDiscordAppRolesError =
  GetDiscordAppRolesErrors[keyof GetDiscordAppRolesErrors];

export type GetDiscordAppRolesResponses = {
  /**
   * Sucessfull Response
   */
  200: {
    [key: string]: {
      id: string;
      name: string;
      owner_id: string;
      members: number;
      icon_url: null | string;
      /**
       * Construct a type with a set of properties K of type T
       */
      roles: {
        [key: string]: {
          name: string;
          position: number;
          color: number;
        };
      };
    };
  };
};

export type GetDiscordAppRolesResponse =
  GetDiscordAppRolesResponses[keyof GetDiscordAppRolesResponses];

export type GetDiscordAppServersData = {
  body?: never;
  path: {
    storeId: string;
  };
  query?: never;
  url: "/stores/{storeId}/app/discord/servers";
};

export type GetDiscordAppServersErrors = {
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Unknown store.
   */
  404: DefaultError;
  /**
   * Unknown error.
   */
  500: DefaultError;
};

export type GetDiscordAppServersError =
  GetDiscordAppServersErrors[keyof GetDiscordAppServersErrors];

export type GetDiscordAppServersResponses = {
  /**
   * Discord guilds listed successfully.
   */
  200: unknown;
};

export type EditDiscordAppTokenData = {
  body?: {
    /**
     * Discord bot token.
     */
    token: string;
  };
  path: {
    storeId: string;
  };
  query?: never;
  url: "/stores/{storeId}/app/discord/token";
};

export type EditDiscordAppTokenErrors = {
  /**
   * Invalid JSON payload.
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Unknown store.
   */
  404: DefaultError;
  /**
   * Bot already configured.
   */
  409: DefaultError;
  /**
   * Payload too large.
   */
  413: DefaultError;
  /**
   * Unprocessable Entity
   */
  422: DefaultError;
  /**
   * Unknown error.
   */
  500: DefaultError;
};

export type EditDiscordAppTokenError =
  EditDiscordAppTokenErrors[keyof EditDiscordAppTokenErrors];

export type EditDiscordAppTokenResponses = {
  /**
   * Discord bot token updated successfully.
   */
  204: void;
};

export type EditDiscordAppTokenResponse =
  EditDiscordAppTokenResponses[keyof EditDiscordAppTokenResponses];

export type DeleteProductCatalogData = {
  body?: never;
  path: {
    storeId: string;
    catalogId: string;
  };
  query?: never;
  url: "/stores/{storeId}/catalogs/{catalogId}";
};

export type DeleteProductCatalogErrors = {
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Not Found
   */
  404: DefaultError;
  /**
   * Unknown error.
   */
  500: DefaultError;
};

export type DeleteProductCatalogError =
  DeleteProductCatalogErrors[keyof DeleteProductCatalogErrors];

export type DeleteProductCatalogResponses = {
  /**
   * Catalog deleted successfully.
   */
  204: void;
};

export type DeleteProductCatalogResponse =
  DeleteProductCatalogResponses[keyof DeleteProductCatalogResponses];

export type EditProductCatalogData = {
  body?: {
    /**
     * Public name. Must be 3 to 50 valid characters.
     */
    name?: string;
    placeholder?: null | string;
    /**
     * Catalog description.
     */
    description?: string;
    color?: null | number;
    /**
     * Items displayed in the catalog.
     */
    items?: Array<{
      product_id?: null | number;
      catalog_id?: null | number;
      emoji?: null | string;
      label?: null | string;
    }>;
  };
  path: {
    storeId: string;
    catalogId: string;
  };
  query?: never;
  url: "/stores/{storeId}/catalogs/{catalogId}";
};

export type EditProductCatalogErrors = {
  /**
   * Invalid JSON payload.
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Not Found
   */
  404: DefaultError;
  /**
   * Payload too large.
   */
  413: DefaultError;
  /**
   * Unprocessable Entity
   */
  422: DefaultError;
  /**
   * Unknown error.
   */
  500: DefaultError;
};

export type EditProductCatalogError =
  EditProductCatalogErrors[keyof EditProductCatalogErrors];

export type EditProductCatalogResponses = {
  /**
   * Catalog updated successfully.
   */
  204: void;
};

export type EditProductCatalogResponse =
  EditProductCatalogResponses[keyof EditProductCatalogResponses];

export type ListProductCatalogsData = {
  body?: never;
  path: {
    storeId: string;
  };
  query?: never;
  url: "/stores/{storeId}/catalogs";
};

export type ListProductCatalogsErrors = {
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Unknown store.
   */
  404: DefaultError;
  /**
   * Unknown error.
   */
  500: DefaultError;
};

export type ListProductCatalogsError =
  ListProductCatalogsErrors[keyof ListProductCatalogsErrors];

export type ListProductCatalogsResponses = {
  /**
   * Catalogs listed successfully.
   */
  200: Array<{
    id: number;
    name: string;
    placeholder: null | string;
    description: null | string;
    created_at: number;
    owner_id: number;
    store_id: number;
    icon_id: null | string;
    banner_id: null | string;
    color: null | number;
    items: Array<{
      product_id: null | number;
      catalog_id: null | number;
      emoji: null | string;
      label: null | string;
    }>;
  }>;
};

export type ListProductCatalogsResponse =
  ListProductCatalogsResponses[keyof ListProductCatalogsResponses];

export type CreateProductCatalogData = {
  body?: {
    /**
     * Public name. Must be 3 to 50 valid characters.
     */
    name: string;
    /**
     * Catalog description.
     */
    description?: string;
    placeholder?: null | string;
  };
  path: {
    storeId: string;
  };
  query?: never;
  url: "/stores/{storeId}/catalogs";
};

export type CreateProductCatalogErrors = {
  /**
   * Invalid JSON payload.
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Unknown store.
   */
  404: DefaultError;
  /**
   * Payload too large.
   */
  413: DefaultError;
  /**
   * Unprocessable Entity
   */
  422: DefaultError;
  /**
   * Unknown error.
   */
  500: DefaultError;
};

export type CreateProductCatalogError =
  CreateProductCatalogErrors[keyof CreateProductCatalogErrors];

export type CreateProductCatalogResponses = {
  /**
   * Catalog created successfully.
   */
  200: {
    /**
     * Catalog ID.
     */
    id: number;
  };
};

export type CreateProductCatalogResponse =
  CreateProductCatalogResponses[keyof CreateProductCatalogResponses];

export type SendProductCatalogMessageData = {
  body?: {
    /**
     * Discord channel id where the catalog message should be posted.
     */
    channel_id: string;
  };
  path: {
    storeId: string;
    catalogId: string;
  };
  query?: never;
  url: "/stores/{storeId}/catalogs/{catalogId}/discord_messages";
};

export type SendProductCatalogMessageErrors = {
  /**
   * Invalid JSON payload.
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Not Found
   */
  404: DefaultError;
  /**
   * Payload too large.
   */
  413: DefaultError;
  /**
   * Unknown channel.
   */
  422: DefaultError;
  /**
   * Unknown error.
   */
  500: DefaultError;
};

export type SendProductCatalogMessageError =
  SendProductCatalogMessageErrors[keyof SendProductCatalogMessageErrors];

export type SendProductCatalogMessageResponses = {
  /**
   * Catalog message queued successfully.
   */
  202: unknown;
};

export type DeleteCouponData = {
  body?: never;
  path: {
    storeId: string;
    couponId: string;
  };
  query?: never;
  url: "/stores/{storeId}/coupons/{couponId}";
};

export type DeleteCouponErrors = {
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Unknown store.
   */
  404: DefaultError;
  /**
   * Unknown error.
   */
  500: DefaultError;
};

export type DeleteCouponError = DeleteCouponErrors[keyof DeleteCouponErrors];

export type DeleteCouponResponses = {
  /**
   * Coupon deleted successfully.
   */
  204: void;
};

export type DeleteCouponResponse =
  DeleteCouponResponses[keyof DeleteCouponResponses];

export type GetCouponData = {
  body?: never;
  path: {
    storeId: string;
    couponId: string;
  };
  query?: never;
  url: "/stores/{storeId}/coupons/{couponId}";
};

export type GetCouponErrors = {
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Unknown store.
   */
  404: DefaultError;
  /**
   * Unknown error.
   */
  500: DefaultError;
};

export type GetCouponError = GetCouponErrors[keyof GetCouponErrors];

export type GetCouponResponses = {
  /**
   * Coupon returned successfully.
   */
  200: unknown;
};

export type EditCouponData = {
  body?: {
    /**
     * Coupon code. Only letters and numbers are allowed.
     */
    name?: string;
    type?: "value" | "percentage";
    /**
     * Coupon discount value. Percentage coupons accept 1 to 100; value coupons accept up to 999999.
     */
    value?: number;
    /**
     * Total uses available for this coupon.
     */
    amount?: number;
    /**
     * Minimum order value required to use this coupon.
     */
    min_value?: number;
    expires_at?: string | number;
    /**
     * Maximum uses per user.
     */
    max_uses_per_user?: number;
    only_first_buy?: boolean;
    /**
     * Product ids allowed for this coupon.
     */
    products?: Array<number>;
    /**
     * Discord role ids allowed to use this coupon. Empty allows any customer not blocked.
     */
    discord_roles_allowed?: Array<string>;
    /**
     * Discord role ids blocked from using this coupon. Blocked wins over allowed.
     */
    discord_roles_blocked?: Array<string>;
  };
  path: {
    storeId: string;
    couponId: string;
  };
  query?: never;
  url: "/stores/{storeId}/coupons/{couponId}";
};

export type EditCouponErrors = {
  /**
   * Invalid JSON payload.
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Not Found
   */
  404: DefaultError;
  /**
   * Payload too large.
   */
  413: DefaultError;
  /**
   * Unprocessable Entity
   */
  422: DefaultError;
  /**
   * Unknown error.
   */
  500: DefaultError;
};

export type EditCouponError = EditCouponErrors[keyof EditCouponErrors];

export type EditCouponResponses = {
  /**
   * Coupon updated successfully.
   */
  204: void;
};

export type EditCouponResponse = EditCouponResponses[keyof EditCouponResponses];

export type ListCouponsData = {
  body?: never;
  path: {
    storeId: string;
  };
  query?: never;
  url: "/stores/{storeId}/coupons";
};

export type ListCouponsErrors = {
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Unknown store.
   */
  404: DefaultError;
  /**
   * Unknown error.
   */
  500: DefaultError;
};

export type ListCouponsError = ListCouponsErrors[keyof ListCouponsErrors];

export type ListCouponsResponses = {
  /**
   * Coupons listed successfully.
   */
  200: unknown;
};

export type CreateCouponData = {
  body?: {
    /**
     * Coupon code. Only letters and numbers are allowed.
     */
    name: string;
    type: "value" | "percentage";
    /**
     * Coupon discount value. Percentage coupons accept 1 to 100; value coupons accept up to 999999.
     */
    value: number;
    /**
     * Total uses available for this coupon.
     */
    amount: number;
    /**
     * Minimum order value required to use this coupon.
     */
    min_value: number;
    /**
     * Expiration timestamp in milliseconds, or 0 for no expiration.
     */
    expires_at: number;
    /**
     * Maximum uses per user.
     */
    max_uses_per_user: number;
    only_first_buy: boolean;
  };
  path: {
    storeId: string;
  };
  query?: never;
  url: "/stores/{storeId}/coupons";
};

export type CreateCouponErrors = {
  /**
   * Invalid JSON payload.
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Unknown store.
   */
  404: DefaultError;
  /**
   * Payload too large.
   */
  413: DefaultError;
  /**
   * Unprocessable Entity
   */
  422: DefaultError;
  /**
   * Unknown error.
   */
  500: DefaultError;
};

export type CreateCouponError = CreateCouponErrors[keyof CreateCouponErrors];

export type CreateCouponResponses = {
  /**
   * Coupon created successfully.
   */
  200: {
    /**
     * Coupon ID.
     */
    id: number;
  };
};

export type CreateCouponResponse =
  CreateCouponResponses[keyof CreateCouponResponses];

export type GetCouponHistoryData = {
  body?: never;
  path: {
    storeId: string;
    couponId: string;
  };
  query?: {
    /**
     * Sale time cursor in ms; only records strictly before are returned.
     */
    before?: string;
    /**
     * Number of history entries (max 50, default 20).
     */
    limit?: string;
    /**
     * Filter by payer (users.core.id, discord_user_id or email).
     */
    to?: string;
  };
  url: "/stores/{storeId}/coupons/{couponId}/history";
};

export type GetCouponHistoryErrors = {
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Unknown store.
   */
  404: DefaultError;
  /**
   * Unknown error.
   */
  500: DefaultError;
};

export type GetCouponHistoryError =
  GetCouponHistoryErrors[keyof GetCouponHistoryErrors];

export type GetCouponHistoryResponses = {
  /**
   * History entries returned in descending order by sale time.
   */
  200: Array<{
    /**
     * Transaction id (transactions.core).
     */
    id: string;
    /**
     * Sale timestamp in ms.
     */
    at: number;
    to: {
      id: number;
      username: string;
      avatar: null | string;
    };
    order: {
      subtotal: number;
      /**
       * Discount applied by this coupon on the order.
       */
      discount: number;
      total_value: number;
      /**
       * Represents the enum public.transaction_status
       */
      status:
        | "pending"
        | "approved"
        | "expired"
        | "cancelled"
        | "refused"
        | "refunded"
        | "analysis"
        | "invalid-pix-key";
      refunded_value: number;
    };
  }>;
};

export type GetCouponHistoryResponse =
  GetCouponHistoryResponses[keyof GetCouponHistoryResponses];

export type DeleteMediaData = {
  body?: {
    store?: Array<
      | "icon"
      | "banner"
      | "background_ranking"
      | "banner_sale_approved"
      | "qrcode_image"
    >;
    /**
     * Construct a type with a set of properties K of type T
     */
    products?: {
      [key: string]: Array<"icon" | "banner">;
    };
    /**
     * Construct a type with a set of properties K of type T
     */
    catalogs?: {
      [key: string]: Array<"icon" | "banner">;
    };
  };
  path: {
    storeId: string;
  };
  query?: never;
  url: "/stores/{storeId}/media";
};

export type DeleteMediaErrors = {
  /**
   * Invalid JSON payload.
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Unknown store.
   */
  404: DefaultError;
  /**
   * Payload too large.
   */
  413: DefaultError;
  /**
   * Unknown error.
   */
  500: DefaultError;
};

export type DeleteMediaError = DeleteMediaErrors[keyof DeleteMediaErrors];

export type DeleteMediaResponses = {
  /**
   * Media detached successfully.
   */
  204: void;
};

export type DeleteMediaResponse =
  DeleteMediaResponses[keyof DeleteMediaResponses];

export type UploadStoreMediaData = {
  body?: {
    file: Blob | File;
    set: {
      store?: Array<
        | "icon"
        | "banner"
        | "background_ranking"
        | "banner_sale_approved"
        | "qrcode_image"
      >;
      /**
       * Construct a type with a set of properties K of type T
       */
      products?: {
        [key: string]: Array<"icon" | "banner">;
      };
      /**
       * Construct a type with a set of properties K of type T
       */
      catalogs?: {
        [key: string]: Array<"icon" | "banner">;
      };
    };
  };
  path: {
    storeId: string;
  };
  query?: never;
  url: "/stores/{storeId}/media";
};

export type UploadStoreMediaErrors = {
  /**
   * Invalid Multipart payload.
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Unknown store.
   */
  404: DefaultError;
  /**
   * Payload too large.
   */
  413: DefaultError;
  /**
   * Unsupported Media Type
   */
  415: DefaultError;
  /**
   * Too many requests.
   */
  429: DefaultError;
  /**
   * Unknown error.
   */
  500: DefaultError;
};

export type UploadStoreMediaError =
  UploadStoreMediaErrors[keyof UploadStoreMediaErrors];

export type UploadStoreMediaResponses = {
  /**
   * Media uploaded successfully.
   */
  201: {
    /**
     * Uploaded media hash.
     */
    hash: string;
  };
};

export type UploadStoreMediaResponse =
  UploadStoreMediaResponses[keyof UploadStoreMediaResponses];

export type GetStoreRankingCustomersData = {
  body?: never;
  path: {
    storeId: string;
  };
  query?: {
    /**
     * Want to see the rankings from the last few days?
     */
    days?: string;
  };
  url: "/stores/{storeId}/ranking/customers";
};

export type GetStoreRankingCustomersErrors = {
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Unknown store.
   */
  404: DefaultError;
  /**
   * Invalid ranking days.
   */
  422: DefaultError;
  /**
   * Unknown error.
   */
  500: DefaultError;
};

export type GetStoreRankingCustomersError =
  GetStoreRankingCustomersErrors[keyof GetStoreRankingCustomersErrors];

export type GetStoreRankingCustomersResponses = {
  /**
   * trade-offs e pontos conhecidos de falha:
   * 1. usuário pode comprar
   * 2. em cache atualiza o lastBuy com a data dessa compra.
   * 3. pedido é reembolsado
   * 4. continua considerando o antigo lastBuy
   */
  200: Array<{
    id: number;
    count: number;
    value: number;
    firstBuy: number;
    lastBuy: number;
  }>;
};

export type GetStoreRankingCustomersResponse =
  GetStoreRankingCustomersResponses[keyof GetStoreRankingCustomersResponses];

export type GetStoreStatsCouponsData = {
  body?: never;
  path: {
    storeId: string;
  };
  query?: never;
  url: "/stores/{storeId}/stats/coupons";
};

export type GetStoreStatsCouponsErrors = {
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Unknown store.
   */
  404: DefaultError;
  /**
   * Unknown error.
   */
  500: DefaultError;
};

export type GetStoreStatsCouponsError =
  GetStoreStatsCouponsErrors[keyof GetStoreStatsCouponsErrors];

export type GetStoreStatsCouponsResponses = {
  /**
   * Store coupon statistics returned successfully.
   */
  200: {
    total: {
      value: number;
      discount: number;
      count: number;
      users: number;
      newUsers: number;
      rating: null | number;
    };
    /**
     * Construct a type with a set of properties K of type T
     */
    coupons: {
      [key: string]: {
        value: number;
        discount: number;
        count: number;
        users: number;
        newUsers: number;
        rating: null | number;
        products: Array<{
          id: number;
          value: number;
          count: number;
        }>;
      };
    };
    /**
     * Construct a type with a set of properties K of type T
     */
    history: {
      [key: string]: {
        [key: string]: {
          value: number;
          discount: number;
          count: number;
          users: number;
          newUsers: number;
          rating: null | number;
        };
      };
    };
  };
};

export type GetStoreStatsCouponsResponse =
  GetStoreStatsCouponsResponses[keyof GetStoreStatsCouponsResponses];

export type GetStoreStatsProductsData = {
  body?: never;
  path: {
    storeId: string;
  };
  query?: never;
  url: "/stores/{storeId}/stats/products";
};

export type GetStoreStatsProductsErrors = {
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Unknown store.
   */
  404: DefaultError;
  /**
   * Unknown error.
   */
  500: DefaultError;
};

export type GetStoreStatsProductsError =
  GetStoreStatsProductsErrors[keyof GetStoreStatsProductsErrors];

export type GetStoreStatsProductsResponses = {
  /**
   * Store product statistics returned successfully.
   */
  200: {
    total: {
      value: number;
      count: number;
      users: number;
      rating: null | number;
    };
    /**
     * Construct a type with a set of properties K of type T
     */
    history: {
      [key: string]: {
        [key: string]: {
          value: number;
          count: number;
          users: number;
          rating: null | number;
        };
      };
    };
  };
};

export type GetStoreStatsProductsResponse =
  GetStoreStatsProductsResponses[keyof GetStoreStatsProductsResponses];

export type GetStoreStatsSalesData = {
  body?: never;
  path: {
    storeId: string;
  };
  query?: never;
  url: "/stores/{storeId}/stats/sales";
};

export type GetStoreStatsSalesErrors = {
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Unknown store.
   */
  404: DefaultError;
  /**
   * Unknown error.
   */
  500: DefaultError;
};

export type GetStoreStatsSalesError =
  GetStoreStatsSalesErrors[keyof GetStoreStatsSalesErrors];

export type GetStoreStatsSalesResponses = {
  /**
   * Store sales statistics returned successfully.
   */
  200: {
    total: {
      value: number;
      count: number;
      users: number;
      rating: null | number;
    };
    /**
     * Construct a type with a set of properties K of type T
     */
    history: {
      [key: string]: {
        value: number;
        count: number;
        users: number;
        rating: null | number;
      };
    };
  };
};

export type GetStoreStatsSalesResponse =
  GetStoreStatsSalesResponses[keyof GetStoreStatsSalesResponses];

export type GetStoreData = {
  body?: never;
  path: {
    storeId: string;
  };
  query?: never;
  url: "/stores/{storeId}";
};

export type GetStoreErrors = {
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Unknown store.
   */
  404: DefaultError;
  /**
   * Too many requests.
   */
  429: DefaultError;
  /**
   * Unknown error.
   */
  500: DefaultError;
};

export type GetStoreError = GetStoreErrors[keyof GetStoreErrors];

export type GetStoreResponses = {
  /**
   * Store data returned successfully.
   */
  200: {
    id: number;
    name: string;
    created_at: number;
    expires_at: number;
    owner_id: number;
    icon_id: null | string;
    banner_id: null | string;
    background_ranking_id: null | string;
    banner_sale_approved_id: null | string;
    qrcode_image_id: null | string;
    blocked_banks: null | Array<string>;
    color: number;
    addons: null | Array<string>;
    limit_product: number;
    limit_discord_server: number;
    /**
     * Construct a type with a set of properties K of type T
     */
    moderators: {
      [key: string]: {
        discord_user_id: null | string;
        username: string;
        created_at: number;
        /**
         * Represents the enum public.permissions_moderators
         */
        permissions: Array<
          | "MANAGE_CATALOGS"
          | "MANAGE_PRODUCTS"
          | "MANAGE_COUPONS"
          | "MANAGE_STORE"
          | "MANAGE_SALES"
          | "VIEW_STATISTICS"
        >;
      };
    };
    discord_bot: {
      id: string;
      cluster: string;
    };
  };
};

export type GetStoreResponse = GetStoreResponses[keyof GetStoreResponses];

export type EditStoreData = {
  body?: {
    /**
     * Public name. Must be 3 to 50 valid characters.
     */
    name?: string;
    blocked_banks?: Array<string>;
    /**
     * Highlight color as a decimal integer, like Discord's accent_color.
     */
    color?: number;
  };
  path: {
    storeId: string;
  };
  query?: never;
  url: "/stores/{storeId}";
};

export type EditStoreErrors = {
  /**
   * Invalid JSON payload.
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Unknown store.
   */
  404: DefaultError;
  /**
   * Payload too large.
   */
  413: DefaultError;
  /**
   * Unprocessable Entity
   */
  422: DefaultError;
  /**
   * Too many requests.
   */
  429: DefaultError;
  /**
   * Unknown error.
   */
  500: DefaultError;
};

export type EditStoreError = EditStoreErrors[keyof EditStoreErrors];

export type EditStoreResponses = {
  /**
   * Store updated successfully.
   */
  204: void;
};

export type EditStoreResponse = EditStoreResponses[keyof EditStoreResponses];

export type GetTransactionData = {
  body?: never;
  path: {
    transactionId: string;
  };
  query?: never;
  url: "/transactions/{transactionId}";
};

export type GetTransactionErrors = {
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * Transaction not found.
   */
  404: DefaultError;
  /**
   * Too many requests.
   */
  429: DefaultError;
  /**
   * Unknown error.
   */
  500: DefaultError;
};

export type GetTransactionError =
  GetTransactionErrors[keyof GetTransactionErrors];

export type GetTransactionResponses = {
  /**
   * Transaction returned successfully.
   */
  200: {
    id: string;
    expires_at: null | number;
    created_at: number;
    /**
     * Represents the enum public.payment_method
     */
    method: "pix" | "boleto";
    /**
     * Represents the enum public.transaction_status
     */
    status:
      | "pending"
      | "approved"
      | "expired"
      | "cancelled"
      | "refused"
      | "refunded"
      | "analysis"
      | "invalid-pix-key";
    value: number;
    /**
     * Represents the enum public.transaction_type
     */
    type: "transfer" | "sale" | "deposit" | "withdraw";
    /**
     * Represents the enum public.payment_entity
     */
    entity: "mercadopago" | "efi" | "semiauto" | "wallet-efi";
    base_value: number;
    refunded_value: number;
    refund_reason:
      | null
      | "fraud"
      | "pix_med"
      | "requested_with_zennify"
      | "requested_with_bank"
      | "stock_out"
      | "stock_low"
      | "by_admin"
      | "internal_error"
      | "internal_reason"
      | "bank_blacklist"
      | "bank_rejected"
      | "coupon_out";
    refund_comment: null | string;
    refund_requested_by: null | number;
    payer_bank: null | string;
    ref_code: null | string;
    metadata: unknown;
    managed: null | boolean;
    pix_e2eid: null | string;
    pix_qrcode: null | string;
    order: null | {
      id: string;
      total_value: number;
      coupon_id: null | number;
      subtotal: number;
      discount: number;
      /**
       * Represents the enum public.platforms
       */
      platform: "discord" | "website" | "marketplace" | "whatsapp" | "telegram";
      discord_guild_id: null | string;
      discord_channel_id: null | string;
      discord_channel_message_id: null | string;
      discord_sale_message: null | string;
      discord_feedback_message: null | string;
      rating: null | number;
      rating_message: null | string;
      coupon_name: null | string;
      /**
       * From T, pick a set of properties whose keys are in the union K
       */
      payer: {
        id: number;
        discord_user_id: null | string;
        username: string;
      };
      /**
       * From T, pick a set of properties whose keys are in the union K
       */
      seller: {
        id: number;
        discord_user_id: null | string;
        username: string;
      };
      /**
       * From T, pick a set of properties whose keys are in the union K
       */
      store: {
        id: number;
        name: string;
        icon_id: null | string;
        banner_id: null | string;
      };
      products: null | Array<{
        id: number;
        name: string;
        icon_id: null | string;
        banner_id: null | string;
        value: number;
        short_description: null | string;
        discord_description: null | string;
        website_description: null | string;
        instructions: null | string;
        amount: number;
        delivered: Array<string>;
      }>;
      discord_roles: null | Array<{
        id: number;
        guild_id: string;
        role_id: string;
        user_id: number;
        rule_id: null | number;
        role_name: null | string;
        role_color_primary: null | number;
        role_color_secondary: null | number;
        remove_in: null | number;
        should_add: boolean;
        given: null | boolean;
        discord_user_id: null | string;
      }>;
    };
    withdraw: null | {
      total_value: number;
      sended_pix_key: null | string;
      fee: number;
      subtotal: number;
      discount: number;
    };
  };
};

export type GetTransactionResponse =
  GetTransactionResponses[keyof GetTransactionResponses];

export type EditTransactionData = {
  body?: {
    status?: "approved" | "cancelled";
    /**
     * Refund amount.
     */
    refund_value?: number;
    /**
     * Refund comment.
     */
    refund_comment?: string;
    metadata?: {
      /**
       * Compile-time marker property for typia transformer.
       *
       * This phantom property carries tag metadata in the type system. It is never
       * assigned at runtime - it exists only for the transformer to read during
       * compilation.
       */
      "typia.tag"?: {
        target: "string" | "number" | "bigint" | "boolean" | "object" | "array";
        kind: "jsonPlugin";
        schema: {
          description: "Transaction metadata.";
          examples: [
            {
              key: "value";
            },
          ];
        };
      };
    };
    [key: string]: unknown;
  };
  path: {
    transactionId: string;
  };
  query?: never;
  url: "/transactions/{transactionId}";
};

export type EditTransactionErrors = {
  /**
   * Bad Request
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Not Found
   */
  404: DefaultError;
  /**
   * Payload too large.
   */
  413: DefaultError;
  /**
   * Unprocessable Entity
   */
  422: DefaultError;
  /**
   * Internal Server Error
   */
  500: DefaultError;
};

export type EditTransactionError =
  EditTransactionErrors[keyof EditTransactionErrors];

export type EditTransactionResponses = {
  /**
   * Transaction update completed successfully.
   */
  200: unknown;
  /**
   * Transaction update accepted.
   */
  202: unknown;
  /**
   * No transaction update was requested.
   */
  204: void;
};

export type EditTransactionResponse =
  EditTransactionResponses[keyof EditTransactionResponses];
