// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "https://api.zennify.app" | (string & {});
};

export type DefaultError = {
  code: string;
  title: string;
  message: string;
};

export type GetServiceHealthData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/health";
};

export type GetServiceHealthResponses = {
  /**
   * All running fine :)
   */
  200: {
    fine: boolean;
    cache: boolean;
    database: boolean;
  };
};

export type GetServiceHealthResponse =
  GetServiceHealthResponses[keyof GetServiceHealthResponses];

export type GetServiceApiSchemaData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/openapi.json";
};

export type GetServiceApiSchemaResponses = {
  /**
   * Success, good work with our API :)
   */
  200: unknown;
};

export type DeleteStoreDiscordPanelData = {
  body?: never;
  path: {
    storeId: string;
    panelId: string;
  };
  query?: never;
  url: "/stores/{storeId}/discord_panels/{panelId}";
};

export type DeleteStoreDiscordPanelErrors = {
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Not Found
   */
  404: DefaultError;
};

export type DeleteStoreDiscordPanelError =
  DeleteStoreDiscordPanelErrors[keyof DeleteStoreDiscordPanelErrors];

export type DeleteStoreDiscordPanelResponses = {
  /**
   * Discord panel deleted successfully.
   */
  204: void;
};

export type DeleteStoreDiscordPanelResponse =
  DeleteStoreDiscordPanelResponses[keyof DeleteStoreDiscordPanelResponses];

export type UpdateStoreDiscordPanelData = {
  body?: {
    /**
     * Public name. Must be 3 to 50 valid characters.
     */
    name?: string;
    placeholder?: null | string;
    /**
     * Discord panel description.
     */
    description?: string;
    /**
     * Products displayed in the panel.
     */
    products?: Array<{
      /**
       * Product id to show in the panel.
       */
      id: number;
      emoji?: null | string;
      label?: null | string;
    }>;
  };
  path: {
    storeId: string;
    panelId: string;
  };
  query?: never;
  url: "/stores/{storeId}/discord_panels/{panelId}";
};

export type UpdateStoreDiscordPanelErrors = {
  /**
   * Invalid JSON payload.
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Not Found
   */
  404: DefaultError;
  /**
   * Payload too large.
   */
  413: DefaultError;
  /**
   * Unprocessable Entity
   */
  422: DefaultError;
};

export type UpdateStoreDiscordPanelError =
  UpdateStoreDiscordPanelErrors[keyof UpdateStoreDiscordPanelErrors];

export type UpdateStoreDiscordPanelResponses = {
  /**
   * Discord panel updated successfully.
   */
  204: void;
};

export type UpdateStoreDiscordPanelResponse =
  UpdateStoreDiscordPanelResponses[keyof UpdateStoreDiscordPanelResponses];

export type GetStoreDiscordPanelsData = {
  body?: never;
  path: {
    storeId: string;
  };
  query?: never;
  url: "/stores/{storeId}/discord_panels";
};

export type GetStoreDiscordPanelsErrors = {
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Unknown store.
   */
  404: DefaultError;
};

export type GetStoreDiscordPanelsError =
  GetStoreDiscordPanelsErrors[keyof GetStoreDiscordPanelsErrors];

export type GetStoreDiscordPanelsResponses = {
  /**
   * Discord panels listed successfully.
   */
  200: unknown;
};

export type CreateStoreDiscordPanelData = {
  body?: {
    /**
     * Public name. Must be 3 to 50 valid characters.
     */
    name: string;
    /**
     * Discord panel description.
     */
    description?: string;
    placeholder?: null | string;
  };
  path: {
    storeId: string;
  };
  query?: never;
  url: "/stores/{storeId}/discord_panels";
};

export type CreateStoreDiscordPanelErrors = {
  /**
   * Invalid JSON payload.
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Unknown store.
   */
  404: DefaultError;
  /**
   * Payload too large.
   */
  413: DefaultError;
  /**
   * Unprocessable Entity
   */
  422: DefaultError;
};

export type CreateStoreDiscordPanelError =
  CreateStoreDiscordPanelErrors[keyof CreateStoreDiscordPanelErrors];

export type CreateStoreDiscordPanelResponses = {
  /**
   * Discord panel created successfully.
   */
  200: {
    /**
     * Discord panel ID.
     */
    id: number;
  };
};

export type CreateStoreDiscordPanelResponse =
  CreateStoreDiscordPanelResponses[keyof CreateStoreDiscordPanelResponses];

export type PostStoreDiscordPanelMessageData = {
  body?: {
    /**
     * Discord channel id where the panel message should be posted.
     */
    channel_id: string;
  };
  path: {
    storeId: string;
    panelId: string;
  };
  query?: never;
  url: "/stores/{storeId}/discord_panels/{panelId}/discord_messages";
};

export type PostStoreDiscordPanelMessageErrors = {
  /**
   * Invalid JSON payload.
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Not Found
   */
  404: DefaultError;
  /**
   * Payload too large.
   */
  413: DefaultError;
  /**
   * Unknown channel.
   */
  422: DefaultError;
};

export type PostStoreDiscordPanelMessageError =
  PostStoreDiscordPanelMessageErrors[keyof PostStoreDiscordPanelMessageErrors];

export type PostStoreDiscordPanelMessageResponses = {
  /**
   * Discord panel message queued successfully.
   */
  202: unknown;
};

export type PostStoreProductDiscordMessageData = {
  body?: {
    /**
     * Discord channel id where the product message should be posted.
     */
    channel_id: string;
  };
  path: {
    storeId: string;
    productId: string;
  };
  query?: never;
  url: "/stores/{storeId}/products/{productId}/discord_messages";
};

export type PostStoreProductDiscordMessageErrors = {
  /**
   * Invalid JSON payload.
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Not Found
   */
  404: DefaultError;
  /**
   * Payload too large.
   */
  413: DefaultError;
  /**
   * Unknown channel.
   */
  422: DefaultError;
};

export type PostStoreProductDiscordMessageError =
  PostStoreProductDiscordMessageErrors[keyof PostStoreProductDiscordMessageErrors];

export type PostStoreProductDiscordMessageResponses = {
  /**
   * Discord product message queued successfully.
   */
  202: unknown;
};

export type DeleteStoreProductData = {
  body?: never;
  path: {
    storeId: string;
    productId: string;
  };
  query?: never;
  url: "/stores/{storeId}/products/{productId}";
};

export type DeleteStoreProductErrors = {
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Unknown store.
   */
  404: DefaultError;
};

export type DeleteStoreProductError =
  DeleteStoreProductErrors[keyof DeleteStoreProductErrors];

export type DeleteStoreProductResponses = {
  /**
   * Product deleted successfully.
   */
  204: void;
};

export type DeleteStoreProductResponse =
  DeleteStoreProductResponses[keyof DeleteStoreProductResponses];

export type GetStoreProductData = {
  body?: never;
  path: {
    storeId: string;
    productId: string;
  };
  query?: never;
  url: "/stores/{storeId}/products/{productId}";
};

export type GetStoreProductErrors = {
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Unknown store.
   */
  404: DefaultError;
};

export type GetStoreProductError =
  GetStoreProductErrors[keyof GetStoreProductErrors];

export type GetStoreProductResponses = {
  /**
   * Product returned successfully.
   */
  200: unknown;
};

export type UpdateStoreProductData = {
  body?: {
    /**
     * Public name. Must be 3 to 50 valid characters.
     */
    name?: string;
    /**
     * Product price in BRL.
     */
    value?: number;
    description?: {
      /**
       * Product description used in Discord messages.
       */
      discord?: string;
    };
  };
  path: {
    storeId: string;
    productId: string;
  };
  query?: never;
  url: "/stores/{storeId}/products/{productId}";
};

export type UpdateStoreProductErrors = {
  /**
   * Invalid JSON payload.
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Unknown store.
   */
  404: DefaultError;
  /**
   * Payload too large.
   */
  413: DefaultError;
  /**
   * Unprocessable Entity
   */
  422: DefaultError;
};

export type UpdateStoreProductError =
  UpdateStoreProductErrors[keyof UpdateStoreProductErrors];

export type UpdateStoreProductResponses = {
  /**
   * Product updated successfully.
   */
  204: void;
};

export type UpdateStoreProductResponse =
  UpdateStoreProductResponses[keyof UpdateStoreProductResponses];

export type GetStoreProductsData = {
  body?: never;
  path: {
    storeId: string;
  };
  query?: never;
  url: "/stores/{storeId}/products";
};

export type GetStoreProductsErrors = {
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Unknown store.
   */
  404: DefaultError;
};

export type GetStoreProductsError =
  GetStoreProductsErrors[keyof GetStoreProductsErrors];

export type GetStoreProductsResponses = {
  /**
   * Products listed successfully.
   */
  200: unknown;
};

export type CreateStoreProductData = {
  body?: {
    /**
     * Public name. Must be 3 to 50 valid characters.
     */
    name: string;
    /**
     * Product price in BRL.
     */
    value: number;
  };
  path: {
    storeId: string;
  };
  query?: never;
  url: "/stores/{storeId}/products";
};

export type CreateStoreProductErrors = {
  /**
   * Invalid JSON payload.
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Unknown store.
   */
  404: DefaultError;
  /**
   * Payload too large.
   */
  413: DefaultError;
  /**
   * Unprocessable Entity
   */
  422: DefaultError;
};

export type CreateStoreProductError =
  CreateStoreProductErrors[keyof CreateStoreProductErrors];

export type CreateStoreProductResponses = {
  /**
   * Product created successfully.
   */
  200: {
    /**
     * Product ID.
     */
    id: number;
  };
};

export type CreateStoreProductResponse =
  CreateStoreProductResponses[keyof CreateStoreProductResponses];

export type UpdateStoreProductStockItemData = {
  body?: {
    /**
     * Private stock content delivered to the buyer.
     */
    content?: string;
    /**
     * Internal cost for this stock item.
     */
    cost?: number;
  };
  path: {
    storeId: string;
    productId: string;
    stockId: string;
  };
  query?: never;
  url: "/stores/{storeId}/products/{productId}/stock/{stockId}";
};

export type UpdateStoreProductStockItemErrors = {
  /**
   * Invalid JSON payload.
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Not Found
   */
  404: DefaultError;
  /**
   * Payload too large.
   */
  413: DefaultError;
  /**
   * Unprocessable Entity
   */
  422: DefaultError;
};

export type UpdateStoreProductStockItemError =
  UpdateStoreProductStockItemErrors[keyof UpdateStoreProductStockItemErrors];

export type UpdateStoreProductStockItemResponses = {
  /**
   * Stock item updated successfully.
   */
  204: void;
};

export type UpdateStoreProductStockItemResponse =
  UpdateStoreProductStockItemResponses[keyof UpdateStoreProductStockItemResponses];

export type GetStoreProductStockData = {
  body?: never;
  path: {
    storeId: string;
    productId: string;
  };
  query?: never;
  url: "/stores/{storeId}/products/{productId}/stock";
};

export type GetStoreProductStockErrors = {
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Unknown store.
   */
  404: DefaultError;
};

export type GetStoreProductStockError =
  GetStoreProductStockErrors[keyof GetStoreProductStockErrors];

export type GetStoreProductStockResponses = {
  /**
   * Stock items listed successfully.
   */
  200: Array<{
    /**
     * Stock item ID.
     */
    id: number;
    /**
     * Private stock content delivered to the buyer.
     */
    content: string;
    /**
     * Internal cost for this stock item.
     */
    cost: number;
  }>;
};

export type GetStoreProductStockResponse =
  GetStoreProductStockResponses[keyof GetStoreProductStockResponses];

export type UpdateStoreProductStockData = {
  body?: {
    stock_locked?: boolean;
    add?: Array<{
      /**
       * Private stock content delivered to the buyer.
       */
      content: string;
      /**
       * Internal cost for this stock item.
       */
      cost: number;
      id?: number;
    }>;
    remove?: Array<number>;
  };
  path: {
    storeId: string;
    productId: string;
  };
  query?: never;
  url: "/stores/{storeId}/products/{productId}/stock";
};

export type UpdateStoreProductStockErrors = {
  /**
   * Invalid JSON payload.
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Unknown store.
   */
  404: DefaultError;
  /**
   * Payload too large.
   */
  413: DefaultError;
  /**
   * Unprocessable Entity
   */
  422: DefaultError;
};

export type UpdateStoreProductStockError =
  UpdateStoreProductStockErrors[keyof UpdateStoreProductStockErrors];

export type UpdateStoreProductStockResponses = {
  /**
   * Product stock updated successfully.
   */
  200: {
    stock_locked: boolean;
    stock: Array<{
      /**
       * Stock item ID.
       */
      id: number;
      /**
       * Private stock content delivered to the buyer.
       */
      content: string;
      /**
       * Internal cost for this stock item.
       */
      cost: number;
    }>;
  };
};

export type UpdateStoreProductStockResponse =
  UpdateStoreProductStockResponses[keyof UpdateStoreProductStockResponses];

export type GetApiReferenceData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/reference";
};

export type GetApiReferenceResponses = {
  /**
   * Success, good work with our API :)
   */
  200:
    | '\n<!doctype html>\n<html>\n    <head>\n        <title>Zennify API Reference</title>\n        <meta charset="utf-8" />\n        <meta name="viewport" content="width=device-width, initial-scale=1" />\n        <meta name="title" content="Zennify API" />\n        <meta name="description" content="Zennify API Documentation" />\n        <meta property="og:description" content="Zennify API Documentation" />\n        <meta property="og:title" content="Zennify API" />\n        <meta property="og:image" content="https://zennify.app/logo.png" />\n        <meta name="twitter:card" content="summary_large_image" />\n    </head>\n    <body>\n        <div id="app"></div>\n        <!-- Load the Script -->\n        <script src="https://cdn.jsdelivr.net/npm/@scalar/api-reference"></script>\n        <!-- Initialize the API Reference -->\n        <script>\n            Scalar.createApiReference("#app", {\n                // The URL of the OpenAPI/Swagger document\n                url: "https://api.zennify.app/openapi.json",\n                // Avoid CORS issues\n                proxyUrl: "",\n                showOperationId: true,\n                persistAuth: true,\n                telemetry: false,\n                theme: "deepSpace",\n            });\n        </script>\n    </body>\n</html>'
    | '\n<!doctype html>\n<html>\n    <head>\n        <title>Zennify API Reference</title>\n        <meta charset="utf-8" />\n        <meta name="viewport" content="width=device-width, initial-scale=1" />\n        <meta name="title" content="Zennify API" />\n        <meta name="description" content="Zennify API Documentation" />\n        <meta property="og:description" content="Zennify API Documentation" />\n        <meta property="og:title" content="Zennify API" />\n        <meta property="og:image" content="https://zennify.app/logo.png" />\n        <meta name="twitter:card" content="summary_large_image" />\n    </head>\n    <body>\n        <div id="app"></div>\n        <!-- Load the Script -->\n        <script src="https://cdn.jsdelivr.net/npm/@scalar/api-reference"></script>\n        <!-- Initialize the API Reference -->\n        <script>\n            Scalar.createApiReference("#app", {\n                // The URL of the OpenAPI/Swagger document\n                url: "https://api.zennify.space/openapi.json",\n                // Avoid CORS issues\n                proxyUrl: "",\n                showOperationId: true,\n                persistAuth: true,\n                telemetry: false,\n                theme: "deepSpace",\n            });\n        </script>\n    </body>\n</html>';
};

export type GetApiReferenceResponse =
  GetApiReferenceResponses[keyof GetApiReferenceResponses];

export type GetServiceDataData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/service";
};

export type GetServiceDataResponses = {
  /**
   * Success - Get service data
   */
  200: {
    servers: Array<{
      /**
       * Discord server id.
       */
      id: string;
      /**
       * Discord server name.
       */
      name: string;
      /**
       * Discord server member count.
       */
      members: number;
      /**
       * Discord server icon URL.
       */
      icon_url: string;
    }>;
    random: Array<{
      /**
       * Discord server id.
       */
      id: string;
      /**
       * Discord server name.
       */
      name: string;
      /**
       * Discord server member count.
       */
      members: number;
      /**
       * Discord server icon URL.
       */
      icon_url: string;
    }>;
    pricing: {
      /**
       * Store plan price.
       */
      store: number;
      /**
       * Store renewal price.
       */
      renew: number;
      limits: {
        /**
         * Discord server limit price.
         */
        discord_server: number;
        /**
         * Product limit price.
         */
        product: number;
      };
    };
    statistics: {
      /**
       * Service revenue.
       */
      revenue: number;
      /**
       * Store count.
       */
      stores: number;
      /**
       * Sales count.
       */
      sales: number;
      /**
       * User count.
       */
      users: number;
    };
  };
};

export type GetServiceDataResponse =
  GetServiceDataResponses[keyof GetServiceDataResponses];

export type UpdateStoreDiscordChannelsData = {
  body?: {
    /**
     * Discord guild and channel binding.
     */
    carts?: {
      /**
       * Discord guild id.
       */
      guild_id: string;
      channel_id?: null | string;
    };
    /**
     * Discord guild and channel binding.
     */
    feedbacks?: {
      /**
       * Discord guild id.
       */
      guild_id: string;
      channel_id?: null | string;
    };
    /**
     * Discord guild and channel binding.
     */
    sales?: {
      /**
       * Discord guild id.
       */
      guild_id: string;
      channel_id?: null | string;
    };
    /**
     * Discord guild and channel binding.
     */
    voice?: {
      /**
       * Discord guild id.
       */
      guild_id: string;
      channel_id?: null | string;
    };
  };
  path: {
    storeId: string;
  };
  query?: never;
  url: "/stores/{storeId}/app/discord/channels";
};

export type UpdateStoreDiscordChannelsErrors = {
  /**
   * Invalid JSON payload.
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Unknown store.
   */
  404: DefaultError;
  /**
   * Payload too large.
   */
  413: DefaultError;
  /**
   * Unprocessable Entity
   */
  422: DefaultError;
};

export type UpdateStoreDiscordChannelsError =
  UpdateStoreDiscordChannelsErrors[keyof UpdateStoreDiscordChannelsErrors];

export type UpdateStoreDiscordChannelsResponses = {
  /**
   * Discord channels updated successfully.
   */
  204: void;
};

export type UpdateStoreDiscordChannelsResponse =
  UpdateStoreDiscordChannelsResponses[keyof UpdateStoreDiscordChannelsResponses];

export type CreateStoreDiscordEmojisData = {
  body?: {
    emojis: Array<Blob | File>;
  };
  path: {
    storeId: string;
    serverId: string;
  };
  query?: never;
  url: "/stores/{storeId}/app/discord/{serverId}/emojis";
};

export type CreateStoreDiscordEmojisErrors = {
  /**
   * Invalid Multipart payload.
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Unknown store.
   */
  404: DefaultError;
  /**
   * Payload too large.
   */
  413: DefaultError;
  /**
   * Unprocessable Entity
   */
  422: DefaultError;
  /**
   * Your actions are being limited.
   */
  429: DefaultError;
};

export type CreateStoreDiscordEmojisError =
  CreateStoreDiscordEmojisErrors[keyof CreateStoreDiscordEmojisErrors];

export type CreateStoreDiscordEmojisResponses = {
  /**
   * Discord emojis created successfully.
   */
  200: Array<{
    /**
     * Discord emoji id.
     */
    id: string;
    /**
     * Discord emoji name.
     */
    name: string;
  }>;
};

export type CreateStoreDiscordEmojisResponse =
  CreateStoreDiscordEmojisResponses[keyof CreateStoreDiscordEmojisResponses];

export type GetStoreDiscordBotData = {
  body?: never;
  path: {
    storeId: string;
  };
  query?: never;
  url: "/stores/{storeId}/app/discord";
};

export type GetStoreDiscordBotErrors = {
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Unknown store.
   */
  404: DefaultError;
};

export type GetStoreDiscordBotError =
  GetStoreDiscordBotErrors[keyof GetStoreDiscordBotErrors];

export type GetStoreDiscordBotResponses = {
  /**
   * Discord bot status returned successfully.
   */
  200:
    | {
        valid: false;
      }
    | {
        valid: true;
        /**
         * Discord bot id.
         */
        id: string;
        /**
         * Discord bot username.
         */
        username: string;
        avatar: null | string;
        /**
         * Discord bot discriminator.
         */
        discriminator: string;
        banner: null | string;
        /**
         * Discord bot bio.
         */
        bio: string;
        guilds: Array<{
          /**
           * Discord guild id.
           */
          id: string;
          /**
           * Discord guild name.
           */
          name: string;
          icon: null | string;
          banner: boolean;
          hasAdmin: boolean;
          /**
           * Approximate guild member count.
           */
          members: number;
        }>;
      };
};

export type GetStoreDiscordBotResponse =
  GetStoreDiscordBotResponses[keyof GetStoreDiscordBotResponses];

export type DeleteStoreDiscordServerData = {
  body?: {
    /**
     * Discord guild id.
     */
    id: string;
  };
  path: {
    storeId: string;
  };
  query?: never;
  url: "/stores/{storeId}/app/discord/servers";
};

export type DeleteStoreDiscordServerErrors = {
  /**
   * Invalid JSON payload.
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Unknown store.
   */
  404: DefaultError;
  /**
   * Payload too large.
   */
  413: DefaultError;
  /**
   * Unprocessable Entity
   */
  422: DefaultError;
};

export type DeleteStoreDiscordServerError =
  DeleteStoreDiscordServerErrors[keyof DeleteStoreDiscordServerErrors];

export type DeleteStoreDiscordServerResponses = {
  /**
   * Discord guild removed successfully.
   */
  204: void;
};

export type DeleteStoreDiscordServerResponse =
  DeleteStoreDiscordServerResponses[keyof DeleteStoreDiscordServerResponses];

export type GetStoreDiscordServersData = {
  body?: never;
  path: {
    storeId: string;
  };
  query?: never;
  url: "/stores/{storeId}/app/discord/servers";
};

export type GetStoreDiscordServersErrors = {
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Unknown store.
   */
  404: DefaultError;
};

export type GetStoreDiscordServersError =
  GetStoreDiscordServersErrors[keyof GetStoreDiscordServersErrors];

export type GetStoreDiscordServersResponses = {
  /**
   * Discord guilds listed successfully.
   */
  200: unknown;
};

export type UpdateStoreDiscordBotTokenData = {
  body?: {
    /**
     * Discord bot token.
     */
    token: string;
  };
  path: {
    storeId: string;
  };
  query?: never;
  url: "/stores/{storeId}/app/discord/token";
};

export type UpdateStoreDiscordBotTokenErrors = {
  /**
   * Invalid JSON payload.
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Unknown store.
   */
  404: DefaultError;
  /**
   * Bot already configured.
   */
  409: DefaultError;
  /**
   * Payload too large.
   */
  413: DefaultError;
  /**
   * Unprocessable Entity
   */
  422: DefaultError;
};

export type UpdateStoreDiscordBotTokenError =
  UpdateStoreDiscordBotTokenErrors[keyof UpdateStoreDiscordBotTokenErrors];

export type UpdateStoreDiscordBotTokenResponses = {
  /**
   * Discord bot token updated successfully.
   */
  204: void;
};

export type UpdateStoreDiscordBotTokenResponse =
  UpdateStoreDiscordBotTokenResponses[keyof UpdateStoreDiscordBotTokenResponses];

export type DeleteStoreCouponData = {
  body?: never;
  path: {
    storeId: string;
    couponId: string;
  };
  query?: never;
  url: "/stores/{storeId}/coupons/{couponId}";
};

export type DeleteStoreCouponErrors = {
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Unknown store.
   */
  404: DefaultError;
};

export type DeleteStoreCouponError =
  DeleteStoreCouponErrors[keyof DeleteStoreCouponErrors];

export type DeleteStoreCouponResponses = {
  /**
   * Coupon deleted successfully.
   */
  204: void;
};

export type DeleteStoreCouponResponse =
  DeleteStoreCouponResponses[keyof DeleteStoreCouponResponses];

export type GetStoreCouponData = {
  body?: never;
  path: {
    storeId: string;
    couponId: string;
  };
  query?: never;
  url: "/stores/{storeId}/coupons/{couponId}";
};

export type GetStoreCouponErrors = {
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Unknown store.
   */
  404: DefaultError;
};

export type GetStoreCouponError =
  GetStoreCouponErrors[keyof GetStoreCouponErrors];

export type GetStoreCouponResponses = {
  /**
   * Coupon returned successfully.
   */
  200: unknown;
};

export type UpdateStoreCouponData = {
  body?: {
    /**
     * Coupon code. Only letters and numbers are allowed.
     */
    name?: string;
    type?: "value" | "percentage";
    /**
     * Coupon discount value. Percentage coupons accept 1 to 100; value coupons accept up to 999999.
     */
    value?: number;
    /**
     * Total uses available for this coupon.
     */
    amount?: number;
    /**
     * Minimum order value required to use this coupon.
     */
    min_value?: number;
    expires_at?: string | number;
    /**
     * Maximum uses per user.
     */
    max_uses_per_user?: number;
    only_first_buy?: boolean;
    /**
     * Product ids allowed for this coupon.
     */
    products?: Array<number>;
    /**
     * Discord role ids allowed for this coupon.
     */
    discord_roles?: Array<string>;
  };
  path: {
    storeId: string;
    couponId: string;
  };
  query?: never;
  url: "/stores/{storeId}/coupons/{couponId}";
};

export type UpdateStoreCouponErrors = {
  /**
   * Invalid JSON payload.
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Not Found
   */
  404: DefaultError;
  /**
   * Payload too large.
   */
  413: DefaultError;
  /**
   * Unprocessable Entity
   */
  422: DefaultError;
};

export type UpdateStoreCouponError =
  UpdateStoreCouponErrors[keyof UpdateStoreCouponErrors];

export type UpdateStoreCouponResponses = {
  /**
   * Coupon updated successfully.
   */
  204: void;
};

export type UpdateStoreCouponResponse =
  UpdateStoreCouponResponses[keyof UpdateStoreCouponResponses];

export type GetStoreCouponsData = {
  body?: never;
  path: {
    storeId: string;
  };
  query?: never;
  url: "/stores/{storeId}/coupons";
};

export type GetStoreCouponsErrors = {
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Unknown store.
   */
  404: DefaultError;
};

export type GetStoreCouponsError =
  GetStoreCouponsErrors[keyof GetStoreCouponsErrors];

export type GetStoreCouponsResponses = {
  /**
   * Coupons listed successfully.
   */
  200: unknown;
};

export type CreateStoreCouponData = {
  body?: {
    /**
     * Coupon code. Only letters and numbers are allowed.
     */
    name: string;
    type: "value" | "percentage";
    /**
     * Coupon discount value. Percentage coupons accept 1 to 100; value coupons accept up to 999999.
     */
    value: number;
    /**
     * Total uses available for this coupon.
     */
    amount: number;
    /**
     * Minimum order value required to use this coupon.
     */
    min_value: number;
    /**
     * Expiration timestamp in milliseconds, or 0 for no expiration.
     */
    expires_at: number;
    /**
     * Maximum uses per user.
     */
    max_uses_per_user: number;
    only_first_buy: boolean;
  };
  path: {
    storeId: string;
  };
  query?: never;
  url: "/stores/{storeId}/coupons";
};

export type CreateStoreCouponErrors = {
  /**
   * Invalid JSON payload.
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Unknown store.
   */
  404: DefaultError;
  /**
   * Payload too large.
   */
  413: DefaultError;
  /**
   * Unprocessable Entity
   */
  422: DefaultError;
};

export type CreateStoreCouponError =
  CreateStoreCouponErrors[keyof CreateStoreCouponErrors];

export type CreateStoreCouponResponses = {
  /**
   * Coupon created successfully.
   */
  200: {
    /**
     * Coupon ID.
     */
    id: number;
  };
};

export type CreateStoreCouponResponse =
  CreateStoreCouponResponses[keyof CreateStoreCouponResponses];

export type CreateStoreEditOrderData = {
  body?: {
    /**
     * Store addons to add.
     */
    addons?: Array<
      "custom_bot" | "divulgation" | "antiraid" | "managed_automod"
    >;
    /**
     * Store limits to increase.
     */
    limits?: {
      /**
       * Discord server limit to set.
       */
      discord_server?: number;
      /**
       * Product limit to set.
       */
      product?: number;
    };
  };
  path: {
    storeId: string;
  };
  query?: never;
  url: "/stores/{storeId}/financial/edit";
};

export type CreateStoreEditOrderErrors = {
  /**
   * Invalid JSON payload.
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Forbidden
   */
  403: DefaultError;
  /**
   * Not Found
   */
  404: DefaultError;
  /**
   * Payload too large.
   */
  413: DefaultError;
  /**
   * Unprocessable Entity
   */
  422: DefaultError;
  /**
   * Unknown error.
   */
  500: DefaultError;
};

export type CreateStoreEditOrderError =
  CreateStoreEditOrderErrors[keyof CreateStoreEditOrderErrors];

export type CreateStoreEditOrderResponses = {
  /**
   * Store edit order created successfully.
   */
  200: {
    /**
     * Payment transaction id.
     */
    id: string;
  };
};

export type CreateStoreEditOrderResponse =
  CreateStoreEditOrderResponses[keyof CreateStoreEditOrderResponses];

export type CreateStoreRenewOrderData = {
  body?: {
    /**
     * Number of months to renew the store.
     */
    months: number;
  };
  path: {
    storeId: string;
  };
  query?: never;
  url: "/stores/{storeId}/financial/renew";
};

export type CreateStoreRenewOrderErrors = {
  /**
   * Invalid JSON payload.
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Forbidden
   */
  403: DefaultError;
  /**
   * Not Found
   */
  404: DefaultError;
  /**
   * Payload too large.
   */
  413: DefaultError;
  /**
   * Unprocessable Entity
   */
  422: DefaultError;
  /**
   * Unknown error.
   */
  500: DefaultError;
};

export type CreateStoreRenewOrderError =
  CreateStoreRenewOrderErrors[keyof CreateStoreRenewOrderErrors];

export type CreateStoreRenewOrderResponses = {
  /**
   * Store renew order created successfully.
   */
  200: {
    /**
     * Payment transaction id.
     */
    id: string;
  };
};

export type CreateStoreRenewOrderResponse =
  CreateStoreRenewOrderResponses[keyof CreateStoreRenewOrderResponses];

export type DeleteStoreMediaData = {
  body?: {
    store?: Array<
      "icon" | "banner" | "banner_sale_approved" | "background_ranking"
    >;
    /**
     * Construct a type with a set of properties K of type T
     */
    products?: {
      [key: string]: Array<"icon" | "banner">;
    };
    /**
     * Construct a type with a set of properties K of type T
     */
    discord_sale_panels?: {
      [key: string]: Array<"icon" | "banner">;
    };
  };
  path: {
    storeId: string;
  };
  query?: never;
  url: "/stores/{storeId}/media";
};

export type DeleteStoreMediaErrors = {
  /**
   * Invalid JSON payload.
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Unknown store.
   */
  404: DefaultError;
  /**
   * Payload too large.
   */
  413: DefaultError;
};

export type DeleteStoreMediaError =
  DeleteStoreMediaErrors[keyof DeleteStoreMediaErrors];

export type DeleteStoreMediaResponses = {
  /**
   * Media detached successfully.
   */
  204: void;
};

export type DeleteStoreMediaResponse =
  DeleteStoreMediaResponses[keyof DeleteStoreMediaResponses];

export type UploadStoreMediaData = {
  body?: {
    file: Blob | File;
    set: {
      store?: Array<
        "icon" | "banner" | "banner_sale_approved" | "background_ranking"
      >;
      /**
       * Construct a type with a set of properties K of type T
       */
      products?: {
        [key: string]: Array<"icon" | "banner">;
      };
      /**
       * Construct a type with a set of properties K of type T
       */
      discord_sale_panels?: {
        [key: string]: Array<"icon" | "banner">;
      };
    };
  };
  path: {
    storeId: string;
  };
  query?: never;
  url: "/stores/{storeId}/media";
};

export type UploadStoreMediaErrors = {
  /**
   * Invalid Multipart payload.
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Unknown store.
   */
  404: DefaultError;
  /**
   * Payload too large.
   */
  413: DefaultError;
  /**
   * Unsupported Media Type
   */
  415: DefaultError;
};

export type UploadStoreMediaError =
  UploadStoreMediaErrors[keyof UploadStoreMediaErrors];

export type UploadStoreMediaResponses = {
  /**
   * Media uploaded successfully.
   */
  201: {
    /**
     * Uploaded media hash.
     */
    hash: string;
  };
};

export type UploadStoreMediaResponse =
  UploadStoreMediaResponses[keyof UploadStoreMediaResponses];

export type RemoveStoreModeratorData = {
  body?: never;
  path: {
    storeId: string;
    modId: string;
  };
  query?: never;
  url: "/stores/{storeId}/moderators/{modId}";
};

export type RemoveStoreModeratorErrors = {
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Not Found
   */
  404: DefaultError;
};

export type RemoveStoreModeratorError =
  RemoveStoreModeratorErrors[keyof RemoveStoreModeratorErrors];

export type RemoveStoreModeratorResponses = {
  /**
   * Moderator deleted successfully.
   */
  204: void;
};

export type RemoveStoreModeratorResponse =
  RemoveStoreModeratorResponses[keyof RemoveStoreModeratorResponses];

export type EditStoreModeratorData = {
  body?: {
    /**
     * Permissions granted to the moderator.
     */
    permissions: Array<
      | "MANAGE_DISCORD_PANELS"
      | "MANAGE_PRODUCTS"
      | "MANAGE_COUPONS"
      | "MANAGE_STORE"
      | "MANAGE_SALES"
      | "VIEW_STATISTICS"
      | "VIEW_DISCKETS"
      | "MANAGE_DISCKETS"
    >;
  };
  path: {
    storeId: string;
    modId: string;
  };
  query?: never;
  url: "/stores/{storeId}/moderators/{modId}";
};

export type EditStoreModeratorErrors = {
  /**
   * Invalid JSON payload.
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Not Found
   */
  404: DefaultError;
  /**
   * Payload too large.
   */
  413: DefaultError;
  /**
   * Invalid permissions.
   */
  422: DefaultError;
};

export type EditStoreModeratorError =
  EditStoreModeratorErrors[keyof EditStoreModeratorErrors];

export type EditStoreModeratorResponses = {
  /**
   * Moderator updated successfully.
   */
  204: void;
};

export type EditStoreModeratorResponse =
  EditStoreModeratorResponses[keyof EditStoreModeratorResponses];

export type AddModeratorToStoreData = {
  body?: {
    /**
     * Permissions granted to the invited moderator.
     */
    permissions: Array<
      | "MANAGE_DISCORD_PANELS"
      | "MANAGE_PRODUCTS"
      | "MANAGE_COUPONS"
      | "MANAGE_STORE"
      | "MANAGE_SALES"
      | "VIEW_STATISTICS"
      | "VIEW_DISCKETS"
      | "MANAGE_DISCKETS"
    >;
  };
  path: {
    storeId: string;
  };
  query?: never;
  url: "/stores/{storeId}/moderators";
};

export type AddModeratorToStoreErrors = {
  /**
   * Invalid JSON payload.
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Unknown store.
   */
  404: DefaultError;
  /**
   * Conflict
   */
  409: DefaultError;
  /**
   * Payload too large.
   */
  413: DefaultError;
  /**
   * Invalid permissions.
   */
  422: DefaultError;
};

export type AddModeratorToStoreError =
  AddModeratorToStoreErrors[keyof AddModeratorToStoreErrors];

export type AddModeratorToStoreResponses = {
  /**
   * Moderator invite created successfully.
   */
  200: {
    /**
     * Moderator invite code.
     */
    code: string;
  };
};

export type AddModeratorToStoreResponse =
  AddModeratorToStoreResponses[keyof AddModeratorToStoreResponses];

export type GetStoreRankingCustomersData = {
  body?: never;
  path: {
    storeId: string;
  };
  query?: {
    /**
     * Want to see the rankings from the last few days?
     */
    days?: string;
  };
  url: "/stores/{storeId}/ranking/customers";
};

export type GetStoreRankingCustomersErrors = {
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Unknown store.
   */
  404: DefaultError;
  /**
   * Invalid ranking days.
   */
  422: DefaultError;
};

export type GetStoreRankingCustomersError =
  GetStoreRankingCustomersErrors[keyof GetStoreRankingCustomersErrors];

export type GetStoreRankingCustomersResponses = {
  /**
   * trade-offs e pontos conhecidos de falha:
   * 1. usuário pode comprar
   * 2. em cache atualiza o lastBuy com a data dessa compra.
   * 3. pedido é reembolsado
   * 4. continua considerando o antigo lastBuy
   */
  200: Array<{
    id: number;
    count: number;
    value: number;
    firstBuy: number;
    lastBuy: number;
  }>;
};

export type GetStoreRankingCustomersResponse =
  GetStoreRankingCustomersResponses[keyof GetStoreRankingCustomersResponses];

export type GetStoreStatsProductsData = {
  body?: never;
  path: {
    storeId: string;
  };
  query?: never;
  url: "/stores/{storeId}/stats/products";
};

export type GetStoreStatsProductsErrors = {
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Unknown store.
   */
  404: DefaultError;
};

export type GetStoreStatsProductsError =
  GetStoreStatsProductsErrors[keyof GetStoreStatsProductsErrors];

export type GetStoreStatsProductsResponses = {
  /**
   * Store product statistics returned successfully.
   */
  200: {
    total: {
      value: number;
      count: number;
      users: number;
      rating: null | number;
    };
    /**
     * Construct a type with a set of properties K of type T
     */
    history: {
      [key: string]: {
        [key: string]: {
          value: number;
          count: number;
          users: number;
          rating: null | number;
        };
      };
    };
  };
};

export type GetStoreStatsProductsResponse =
  GetStoreStatsProductsResponses[keyof GetStoreStatsProductsResponses];

export type GetStoreData = {
  body?: never;
  path: {
    storeId: string;
  };
  query?: never;
  url: "/stores/{storeId}";
};

export type GetStoreErrors = {
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Unknown store.
   */
  404: DefaultError;
};

export type GetStoreError = GetStoreErrors[keyof GetStoreErrors];

export type GetStoreResponses = {
  /**
   * Store data returned successfully.
   */
  200: {
    id: number;
    name: string;
    created_at: number;
    expires_at: number;
    owner_id: number;
    icon_id?: null | string;
    banner_id?: null | string;
    background_ranking_id?: null | string;
    banner_sale_approved_id?: null | string;
    blocked_banks?: null | Array<string>;
    addons: Array<
      "custom_bot" | "divulgation" | "antiraid" | "managed_automod"
    >;
    limit_product: number;
    limit_discord_server: number;
    /**
     * Construct a type with a set of properties K of type T
     */
    moderators: {
      [key: string]: {
        username: string;
        discord_user_id: string;
        permissions: Array<
          | "MANAGE_DISCORD_PANELS"
          | "MANAGE_PRODUCTS"
          | "MANAGE_COUPONS"
          | "MANAGE_STORE"
          | "MANAGE_SALES"
          | "VIEW_STATISTICS"
          | "VIEW_DISCKETS"
          | "MANAGE_DISCKETS"
        >;
        created_at: number;
      };
    };
    discord_bot: {
      id: string;
      cluster: string;
    };
  };
};

export type GetStoreResponse = GetStoreResponses[keyof GetStoreResponses];

export type UpdateStoreData = {
  body?: {
    /**
     * Public name. Must be 3 to 50 valid characters.
     */
    name?: string;
    blocked_banks?: Array<string>;
  };
  path: {
    storeId: string;
  };
  query?: never;
  url: "/stores/{storeId}";
};

export type UpdateStoreErrors = {
  /**
   * Invalid JSON payload.
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * This store has expired.
   */
  402: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Unknown store.
   */
  404: DefaultError;
  /**
   * Payload too large.
   */
  413: DefaultError;
  /**
   * Unprocessable Entity
   */
  422: DefaultError;
};

export type UpdateStoreError = UpdateStoreErrors[keyof UpdateStoreErrors];

export type UpdateStoreResponses = {
  /**
   * Store updated successfully.
   */
  204: void;
};

export type UpdateStoreResponse =
  UpdateStoreResponses[keyof UpdateStoreResponses];

export type GetStoresData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/stores";
};

export type GetStoresErrors = {
  /**
   * User not authenticated.
   */
  401: DefaultError;
};

export type GetStoresError = GetStoresErrors[keyof GetStoresErrors];

export type GetStoresResponses = {
  /**
   * Stores listed successfully.
   */
  200: Array<{
    id: number;
    name: string;
    created_at: number;
    expires_at: number;
    icon_id: null | string;
    banner_id: null | string;
    is_owner: boolean;
  }>;
};

export type GetStoresResponse = GetStoresResponses[keyof GetStoresResponses];

export type CreateStoreData = {
  body?: {
    /**
     * Public name. Must be 3 to 50 valid characters.
     */
    name: string;
  };
  path?: never;
  query?: never;
  url: "/stores";
};

export type CreateStoreErrors = {
  /**
   * Invalid JSON payload.
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * PIX not configured.
   */
  403: DefaultError;
  /**
   * Not Found
   */
  404: DefaultError;
  /**
   * Payload too large.
   */
  413: DefaultError;
  /**
   * Unprocessable Entity
   */
  422: DefaultError;
  /**
   * Unknown error.
   */
  500: DefaultError;
};

export type CreateStoreError = CreateStoreErrors[keyof CreateStoreErrors];

export type CreateStoreResponses = {
  /**
   * Store checkout order created successfully.
   */
  200: {
    id: string;
  };
};

export type CreateStoreResponse =
  CreateStoreResponses[keyof CreateStoreResponses];

export type ListTransactionsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Transaction id or Pix E2E id.
     */
    q?: string;
    /**
     * Maximum creation date.
     */
    before?: string;
    /**
     * Transaction status filter.
     */
    status?: string;
    /**
     * Transaction value filter.
     */
    value?: string;
    /**
     * Transaction type filter.
     */
    type?: string;
    /**
     * Maximum number of transactions.
     */
    limit?: string;
    /**
     * User id or Discord user id filter.
     */
    user?: string;
  };
  url: "/transactions";
};

export type ListTransactionsErrors = {
  /**
   * User not authenticated.
   */
  401: DefaultError;
};

export type ListTransactionsError =
  ListTransactionsErrors[keyof ListTransactionsErrors];

export type ListTransactionsResponses = {
  /**
   * Transactions listed successfully.
   */
  200: unknown;
};

export type GetTransactionData = {
  body?: never;
  path: {
    transactionId: string;
  };
  query?: never;
  url: "/transactions/{transactionId}";
};

export type GetTransactionErrors = {
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * Transaction not found.
   */
  404: DefaultError;
};

export type GetTransactionError =
  GetTransactionErrors[keyof GetTransactionErrors];

export type GetTransactionResponses = {
  /**
   * Transaction returned successfully.
   */
  200: {
    id: string;
    status:
      | "approved"
      | "cancelled"
      | "refunded"
      | "inactive"
      | "invalid-pix-key"
      | "pending"
      | "expired"
      | "refused"
      | "analysis";
    value: number;
    method: "pix" | "boleto";
    created_at: number;
    expires_at: number;
    type: "transfer" | "sale" | "deposit" | "withdraw";
    entity: "mercadopago" | "semiauto" | "efi" | "wallet-efi";
    managed?: null | boolean;
    base_value: number;
    refunded_value: number;
    refund_reason?:
      | null
      | "fraud"
      | "pix_med"
      | "by_admin"
      | "requested_with_zennify"
      | "requested_with_bank"
      | "stock_out"
      | "stock_low"
      | "internal_reason"
      | "internal_error"
      | "bank_blacklist"
      | "bank_rejected"
      | "coupon_out";
    refund_comment?: null | string;
    refund_requested_by?: null | number;
    pix_e2eid?: null | string;
    pix_qrcode?: null | string;
    payer_bank?: null | string;
    metadata?: unknown;
    order: {
      id: string;
      subtotal: number;
      discount: number;
      total_value: number;
      platform: "discord" | "website" | "marketplace" | "whatsapp" | "telegram";
      discord_guild_id?: null | string;
      discord_channel_id?: null | string;
      discord_channel_message_id?: null | string;
      discord_sale_message?: null | string;
      discord_feedback_message?: null | string;
      rating?: null | number;
      rating_message?: null | string;
      /**
       * From T, pick a set of properties whose keys are in the union K
       */
      payer: {
        id: number;
        username: string;
        discord_user_id: string;
      };
      /**
       * From T, pick a set of properties whose keys are in the union K
       */
      store: {
        id: number;
        name: string;
        icon_id?: null | string;
        banner_id?: null | string;
      };
      /**
       * From T, pick a set of properties whose keys are in the union K
       */
      seller: {
        id: number;
        username: string;
        discord_user_id: string;
      };
      products: Array<{
        id: number;
        name: string;
        value: number;
        icon_id?: null | string;
        banner_id?: null | string;
        short_description?: null | string;
        discord_description?: null | string;
        website_description?: null | string;
        amount: number;
        delivered: Array<string>;
      }>;
    };
    /**
     * From T, pick a set of properties whose keys are in the union K
     */
    withdraw: {
      fee: number;
      subtotal: number;
      discount: number;
      total_value: number;
      sended_pix_key: null | string;
    };
  };
};

export type GetTransactionResponse =
  GetTransactionResponses[keyof GetTransactionResponses];

export type UpdateTransactionData = {
  body?: {
    status?: "approved" | "cancelled" | "refunded";
    /**
     * Refund amount.
     */
    refund_value?: number;
    /**
     * Refund comment.
     */
    refund_comment?: string;
    metadata?: {
      /**
       * Compile-time marker property for typia transformer.
       *
       * This phantom property carries tag metadata in the type system. It is never
       * assigned at runtime - it exists only for the transformer to read during
       * compilation.
       */
      "typia.tag"?: {
        target: "string" | "number" | "bigint" | "boolean" | "object" | "array";
        kind: "jsonPlugin";
        schema: {
          description: "Transaction metadata.";
          examples: [
            {
              key: "value";
            },
          ];
        };
      };
    };
    [key: string]: unknown;
  };
  path: {
    transactionId: string;
  };
  query?: never;
  url: "/transactions/{transactionId}";
};

export type UpdateTransactionErrors = {
  /**
   * Bad Request
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * Permission denied.
   */
  403: DefaultError;
  /**
   * Not Found
   */
  404: DefaultError;
  /**
   * Order already refunded.
   */
  409: DefaultError;
  /**
   * Payload too large.
   */
  413: DefaultError;
  /**
   * Unprocessable Entity
   */
  422: DefaultError;
  /**
   * Internal Server Error
   */
  500: DefaultError;
};

export type UpdateTransactionError =
  UpdateTransactionErrors[keyof UpdateTransactionErrors];

export type UpdateTransactionResponses = {
  /**
   * Transaction update completed successfully.
   */
  200: unknown;
  /**
   * Transaction update accepted.
   */
  202: unknown;
  /**
   * No transaction update was requested.
   */
  204: void;
};

export type UpdateTransactionResponse =
  UpdateTransactionResponses[keyof UpdateTransactionResponses];

export type GetUserByIdData = {
  body?: never;
  path: {
    userId: string;
  };
  query?: never;
  url: "/users/{userId}";
};

export type GetUserByIdErrors = {
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * User not found.
   */
  404: DefaultError;
};

export type GetUserByIdError = GetUserByIdErrors[keyof GetUserByIdErrors];

export type GetUserByIdResponses = {
  /**
   * Successful response
   */
  200: {
    id: number;
    name: string;
    avatar?: null | string;
    connections: {
      discord: string;
    };
  };
};

export type GetUserByIdResponse =
  GetUserByIdResponses[keyof GetUserByIdResponses];

export type UpdateUserAvatarData = {
  body?: {
    file: Blob | File;
  };
  path?: never;
  query?: never;
  url: "/users/me/avatar";
};

export type UpdateUserAvatarErrors = {
  /**
   * Invalid Multipart payload.
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * No file uploaded.
   */
  404: DefaultError;
  /**
   * Payload Too Large
   */
  413: DefaultError;
};

export type UpdateUserAvatarError =
  UpdateUserAvatarErrors[keyof UpdateUserAvatarErrors];

export type UpdateUserAvatarResponses = {
  /**
   * Avatar updated successfuly
   */
  200: {
    /**
     * Uploaded avatar hash.
     */
    hash: string;
  };
};

export type UpdateUserAvatarResponse =
  UpdateUserAvatarResponses[keyof UpdateUserAvatarResponses];

export type GetUserData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/users/me";
};

export type GetUserErrors = {
  /**
   * User not authenticated.
   */
  401: DefaultError;
};

export type GetUserError = GetUserErrors[keyof GetUserErrors];

export type GetUserResponses = {
  /**
   * Successful response
   */
  200: {
    /**
     * User ID.
     */
    id: number;
    /**
     * Public user name.
     */
    name: string;
    /**
     * User email.
     */
    email: string;
    /**
     * User avatar hash.
     */
    avatar?: string;
    /**
     * Configured webhook URL.
     */
    webhook?: string;
    /**
     * User timezone.
     */
    timezone?: string;
    /**
     * User creation timestamp.
     */
    joinedAt: number;
    payment: {
      entities: {
        efi: {
          id?: string;
          /**
           * Configured Pix key.
           */
          pixKey?: string;
        };
        mercadopago: {
          id?: string;
          /**
           * Configured Pix key.
           */
          pixKey?: string;
        };
        semiauto: {
          id?: string;
          /**
           * Configured Pix key.
           */
          pixKey?: string;
        };
        "wallet-efi": {
          id?: string;
          /**
           * Configured Pix key.
           */
          pixKey?: string;
        };
      };
      preferences: {
        pix: null | "mercadopago" | "semiauto" | "efi" | "wallet-efi";
      };
    };
    connections: {
      discord?: string;
    };
    legal: {
      status?: "pending" | "approved" | "rejected";
      type?: "cpf" | "cnpj";
      rejectedReason?: string;
    };
  };
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type EditUserData = {
  body?: {
    /**
     * Public name. Must be 3 to 50 valid characters.
     */
    name: string;
  };
  path?: never;
  query?: never;
  url: "/users/me";
};

export type EditUserErrors = {
  /**
   * Invalid JSON payload.
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * Payload too large.
   */
  413: DefaultError;
  /**
   * Invalid name.
   */
  422: DefaultError;
};

export type EditUserError = EditUserErrors[keyof EditUserErrors];

export type EditUserResponses = {
  /**
   * User modified succesfully
   */
  204: void;
};

export type EditUserResponse = EditUserResponses[keyof EditUserResponses];

export type UpdatePaymentMethodData = {
  body?: {
    pix: null | string;
  };
  path?: never;
  query?: never;
  url: "/users/me/payment-method";
};

export type UpdatePaymentMethodErrors = {
  /**
   * Invalid JSON payload.
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * Payload too large.
   */
  413: DefaultError;
  /**
   * Invalid payment method.
   */
  422: DefaultError;
};

export type UpdatePaymentMethodError =
  UpdatePaymentMethodErrors[keyof UpdatePaymentMethodErrors];

export type UpdatePaymentMethodResponses = {
  /**
   * Payment method updated.
   */
  204: void;
};

export type UpdatePaymentMethodResponse =
  UpdatePaymentMethodResponses[keyof UpdatePaymentMethodResponses];

export type SetupEfiData = {
  body?: {
    certificate: Blob | File;
    pix_key: string;
    client_id: string;
    client_secret: string;
  };
  path?: never;
  query?: never;
  url: "/users/me/payments/efi/setup";
};

export type SetupEfiErrors = {
  /**
   * Bad Request
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * Forbidden
   */
  403: DefaultError;
  /**
   * Invalid certificate.
   */
  415: DefaultError;
  /**
   * Unprocessable Entity
   */
  422: DefaultError;
  /**
   * Internal Server Error
   */
  500: DefaultError;
};

export type SetupEfiError = SetupEfiErrors[keyof SetupEfiErrors];

export type SetupEfiResponses = {
  /**
   * Efí integration configured. Returns account ID
   */
  200: {
    /**
     * Efí account ID.
     */
    id: string;
  };
};

export type SetupEfiResponse = SetupEfiResponses[keyof SetupEfiResponses];

export type UpdatePixKeyData = {
  body?: {
    /**
     * Pix key.
     */
    pix_key: string;
  };
  path?: never;
  query?: never;
  url: "/users/me/pix_key";
};

export type UpdatePixKeyErrors = {
  /**
   * Invalid JSON payload.
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * Payload too large.
   */
  413: DefaultError;
  /**
   * Unprocessable Entity
   */
  422: DefaultError;
};

export type UpdatePixKeyError = UpdatePixKeyErrors[keyof UpdatePixKeyErrors];

export type UpdatePixKeyResponses = {
  /**
   * Pix key updated or unchanged.
   */
  204: void;
};

export type UpdatePixKeyResponse =
  UpdatePixKeyResponses[keyof UpdatePixKeyResponses];

export type WalletBalanceData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/users/me/wallet/balance";
};

export type WalletBalanceErrors = {
  /**
   * User not authenticated.
   */
  401: DefaultError;
};

export type WalletBalanceError = WalletBalanceErrors[keyof WalletBalanceErrors];

export type WalletBalanceResponses = {
  /**
   * Balance returned successfully.
   */
  200: {
    /**
     * Pending wallet balance.
     */
    pending: number;
    /**
     * Available wallet balance.
     */
    available: number;
  };
};

export type WalletBalanceResponse =
  WalletBalanceResponses[keyof WalletBalanceResponses];

export type WalletWithdrawData = {
  body?: {
    /**
     * Money value.
     */
    value: number;
    automatic: boolean;
  };
  path?: never;
  query?: never;
  url: "/users/me/wallet/withdraw";
};

export type WalletWithdrawErrors = {
  /**
   * Invalid JSON payload.
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * Conflict
   */
  409: DefaultError;
  /**
   * Payload too large.
   */
  413: DefaultError;
  /**
   * Invalid parameter.
   */
  422: DefaultError;
  /**
   * Withdrawal limit exceeded.
   */
  429: DefaultError;
};

export type WalletWithdrawError =
  WalletWithdrawErrors[keyof WalletWithdrawErrors];

export type WalletWithdrawResponses = {
  /**
   * Withdraw requested succesfully.
   */
  200: {
    /**
     * Withdraw transaction ID.
     */
    id: string;
  };
};

export type WalletWithdrawResponse =
  WalletWithdrawResponses[keyof WalletWithdrawResponses];

export type SetupWebhookData = {
  body?: {
    /**
     * HTTPS URL.
     */
    url: string;
  };
  path?: never;
  query?: never;
  url: "/users/me/webhook";
};

export type SetupWebhookErrors = {
  /**
   * Invalid JSON payload.
   */
  400: DefaultError;
  /**
   * User not authenticated.
   */
  401: DefaultError;
  /**
   * URL timeout exceeded.
   */
  408: DefaultError;
  /**
   * Payload too large.
   */
  413: DefaultError;
  /**
   * Unprocessable Entity
   */
  422: DefaultError;
  /**
   * URL inaccessible.
   */
  424: DefaultError;
};

export type SetupWebhookError = SetupWebhookErrors[keyof SetupWebhookErrors];

export type SetupWebhookResponses = {
  /**
   * Webhook configured successfully.
   */
  204: void;
};

export type SetupWebhookResponse =
  SetupWebhookResponses[keyof SetupWebhookResponses];
