export type APIErrors =
    // 0-1000 = general errors
    | 'UNKNOWN_ERROR'
    | 'UNKNOWN_TRANSLATION'
    | 'METHOD_NOT_ALLOWED'
    | 'EXPECTED_AN_OBJECT_ARRAY'
    | 'EXPECTED_A_STRING_ARRAY'
    | 'EXPECTED_A_NUMBER_ARRAY'
    | 'EXPECTED_AN_OBJECT'
    | 'EXPECTED_A_NON_EMPTY_OBJECT'
    | 'EXPECTED_A_STRING'
    | 'EXPECTED_A_NUMBER'
    | 'DUPLICATED_VALUES_ISNT_ALLOWED'
    // 1000-1100 = oAuth errors
    | 'GRANT_CODE_MISSING_IN_QUERY'
    | 'INVALID_SCOPE'
    | 'VERIFY_YOUR_EMAIL'
    | 'PLEASE_REVERIFY'
    // 1500-2000 = user errors
    | 'USER_NOT_FOUND'
    // 1501 - 1510
    // password errors
    | 'INSERT_A_VALID_PASSWORD'
    | 'YOU_MUST_INSERT_THE_ACTUAL_PASSWORD'
    | 'THE_PASSWORD_DOES_NOT_MATCH'
    | 'THE_PASSWORD_MUST_HAVE_AT_LEAST_8_CHARACTERS'
    | 'THE_PASSWORD_MUST_HAVE_AT_LEAST_ONE_NUMBER'
    | 'THE_PASSWORD_MUST_HAVE_AT_LEAST_ONE_LETTER'
    | 'THE_PASSWORD_MUST_HAVE_AT_LEAST_ONE_SPECIAL_CHARACTER'
    // 1511 - 1520
    // pix key errors
    | 'THE_PIX_KEY_SENDED_ISNT_A_VALID_STRING'
    | 'THE_EMAIL_SENDED_ISNT_VALID'
    | 'CELLPHONE_NUMBERS_MUST_HAVE_THE_9_DIGIT'
    | 'THE_CELLPHONE_NUMBER_MUST_HAVE_ONLY_DIGITS'
    | 'THE_PIX_KEY_INSERTED_ISNT_VALID'
    // 1521 - 1530
    // webhook url error
    | 'INSERT_A_VALID_URL'
    | 'THE_ONLY_ACCEPTED_PROTOCOL_IS_HTTPS'
    | 'THIS_DOMAIN_IS_BLACKLISTED'
    | 'THE_URL_EXTENSION_ISNT_ACCEPTED_YET'
    | 'THE_URL_IS_INACCESSIBLE_BY_THE_WEBHOOK_SERVER'
    | 'THE_URL_WOULD_NOT_HAVE_REDIRECTS'
    | 'THE_URL_HAS_TIMEOUT_5S'
    // 2000-3000 = payment errors
    | 'INVALID_PAYMENT_METHOD'
    // 2200-2500
    // Order Errors
    | 'YOU_NEED_TO_INSERT_AT_LEAST_1_ITEM'
    | 'ONE_PROVIDED_PRODUCT_IS_OUT_OF_STOCK'
    | 'WE_DONT_HAVE_THIS_AMOUNT_IN_STOCK'
    | 'THIS_SELLER_WAS_BANNED_FROM_ZENNIFY'
    | 'WE_DO_NOT_YET_SUPPORT_MULTIPLE_USER_PRODUCTS'
    | 'WE_DO_NOT_YET_SUPPORT_MULTIPLE_STORE_PRODUCTS'
    | 'YOU_ALREADY_HAVE_ANOTHER_ORDER_WAITING_PAYMENT'
    | 'YOU_INSERTED_AN_INVALID_ADDITIONAL'
    // 2211 - 2250
    // subtype
    // bad preference configuration
    | 'THIS_SELLER_HAS_NOT_YET_CONFIGURED_RECEIPT_VIA_PIX'
    | 'THIS_SELLER_HAS_NOT_YET_CONFIGURED_RECEIPT_VIA_BOLETO'
    | 'THIS_SELLER_HAS_NOT_YET_CONFIGURED_RECEIPT_VIA_CRYPTO'
    // 2251 - 2275
    // subtype
    // coupons
    | 'THIS_COUPON_DOES_NOT_EXISTS'
    | 'THIS_COUPON_HAS_EXPIRED'
    | 'THIS_COUPON_REACHED_THE_USE_LIMIT'
    | 'YOU_NEED_TO_SELECT_MORE_ITENS_DO_REACH_THE_MINIMUM_VALUE_OF_THE_COUPON'
    | 'THIS_COUPON_IS_VALID_ONLY_FOR_THE_FIRST_BUY'
    // 2500 - 2600 = store errors
    | 'UNKNOWN_STORE'
    | 'UNKNOWN_BANK'
    | 'INVALID_STORE_NAME'
    // 2600 - 3000 = product errors
    | 'UNKNOWN_PRODUCT'
    | 'INVALID_PRODUCT_NAME'
    | 'INVALID_PRODUCT_VALUE'
    | 'YOU_REACHED_THE_PRODUCT_LIMIT'
    | 'YOU_ALREADY_HAVE_ANOTHER_PRODUCT_WITH_THIS_NAME'
    // 2605 - 2610
    // Description errors
    | 'INVALID_DISCORD_DESCRIPTION'
    // 2611 - 2650
    // Stock errors
    | 'INVALID_STOCK_ID'
    | 'UNKNOWN_STOCK'
    | 'INVALID_STOCK_CONTENT'
    | 'INVALID_STOCK_COST'
    // 3001 - 3100 = Media Errors
    | 'UNKNOWN_FILE'
    | 'NO_FILES_FOUND'
    | 'INVALID_FILE_TYPE'
    | 'INVALID_FILE_NAME'
    | 'INVALID_FILE_SIZE'
    | 'YOU_REACHED_THE_MAXIMUM_STORAGE'
    | 'YOU_REACHED_THE_MAXIMUM_MEDIA_COUNT'
    | 'YOU_ALREADY_HAVE_THIS_IMAGE_ON_ZENNIFY'
    | 'YOU_ALREADY_HAVE_ANOTHER_IMAGE_WITH_THIS_NAME'
    // 3101 - 3200 = Discord Panels Errors
    | 'UNKNOWN_PANEL'
    | 'INVALID_PANEL_NAME'
    | 'INVALID_PANEL_DESCRIPTION'
    | 'INVALID_PANEL_PLACEHOLDER'
    | 'YOU_REACHED_THE_PANEL_LIMIT'
    | 'YOU_ALREADY_HAVE_ANOTHER_PANEL_WITH_THIS_NAME'
    | 'YOU_REACHED_THE_PRODUCTS_LIMIT_ON_PANEL'